force-app/main/default/objects/Contact_Address_field__c/Contact_Address_field__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contact Address field</label>
</CustomObject>

force-app/main/default/objects/Contact_Address_field__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing_City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address_field__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing_Country</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address_field__c/fields/Mailing_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Province__c</fullName>
    <label>Mailing_State_Province</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address_field__c/fields/Mailing_Street__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street__c</fullName>
    <label>Mailing_Street</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address_field__c/fields/Mailing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Postal_Code__c</fullName>
    <label>Mailing_Zip_Postal_Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactNewOverrideController_Test.cls
/**********************************************
/* Name : ContactNewOverrideController_Test
/* Created By : Shubham
/* Case : 00138614
/*********************************************/
@isTest
private class ContactNewOverrideController_Test {

    static testMethod void myUnitTest() {
        Contact c = new Contact();
        c.LastName = 'Test';
        insert c ;
        
        //START -- Added by Shivani for S-637724 on 02/09/2019
        Contact_Address_field__c cAddress = new Contact_Address_field__c();
        cAddress.Name = 'Address';
        cAddress.Mailing_Zip_Postal_Code__c = '12345';
        cAddress.Mailing_City__c = 'TestCity';
        cAddress.Mailing_Country__c = 'TestCountry';
        cAddress.Mailing_State_Province__c = 'TestState';
        cAddress.Mailing_Street__c = 'TestStreet';
        insert cAddress;
        //END -- Added by Shivani for S-637724 on 02/09/2019

        Account acc = new Account();
        acc.Name = 'AccTest';
        insert acc;
        
        c.AccountId = acc.id;
        update c;
        
        //START -- Added by Shivani for S-637724 on 02/09/2019
        Test.setCurrentPageReference(new PageReference('Page.ContactEditOverride')); 
        System.currentPageReference().getParameters().put('accid', acc.Id);
        System.currentPageReference().getParameters().put('RecordType', [SELECT id,Name FROM RecordType where SobjectType='Contact' and Name='PSA Resource'][0].Name);
        System.currentPageReference().getParameters().put('retURL', '/003/e');
        //END -- Added by Shivani for S-637724 on 02/09/2019

        ContactNewOverrideController controller = new ContactNewOverrideController(new Apexpages.Standardcontroller(c));
        controller.redirect();
    }
}