force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>This is the alias for a milestone.</description>
    <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
    <label>Deliverable Alias</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>TMG Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task.</inlineHelpText>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>Task Target Due Date</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Task_Stage__c.field-meta.xml
<CustomField>
    <fullName>Task_Stage__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <inlineHelpText>Where is this task on the road to completion?</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assigned</fullName>
            </value>
            <value>
                <fullName>To Be Scheduled</fullName>
            </value>
            <value>
                <fullName>Client Contacted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled by TMG</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>TBR (To Be Rescheduled)</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>To Be Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Confirmed</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Incomplete (Calendar Conflicts)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DueDateTaskUpdatedBatchTest.cls
/*********************************************************************************
Name : Harendra Sain
Created By : Appirio  
Created Date : 17 Dec 2015
Purpose : Test Class for  DueDateTaskUpdatedBatchTest
*********************************************************************************/
@isTest
public class DueDateTaskUpdatedBatchTest {
   
    static testMethod  void  testTaskDueDate(){
      
         Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' limit 1];
         UserRole role = [SELECT Id FROM UserRole WHERE Name = 'Miles Group' limit 1]; 
         User u = createTestUser(p.Id, role.id, 'test','user1');
         System.runAs ( u ){
         
         //RecordType rt = [select id,Name from RecordType where SobjectType='Milestone1_Task__c' and Name='Highlight & Summarize' Limit 1]; //Updated by Jasvinder for case: 00204418
         Id rtId = Schema.SObjectType.Milestone1_Task__c.RecordTypeInfosByName.get('All Functions').RecordTypeId;

         String taskName = 'Unit Test Email Notes 123';
         Test.StartTest();//Added for case 254740
            Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProject('proj');
            insert proj;

            Milestone1_Milestone__c ms1 = Milestone1_Test_Utility.sampleMilestone(proj.Id, null, 'ms1');
            ms1.Alias__c = 'unit_test';
            insert ms1;

            Milestone1_Task__c msTask1 = Milestone1_Test_Utility.sampleTask(ms1.Id);
            msTask1.recordTypeId = rtId;
            msTask1.Name = taskName;
       
            msTask1.Assigned_To__c = u.id ;
            msTask1.Task_Stage__c  = 'Scheduled';
            msTask1.Due_Date__c = System.today().addDays(-7);
            insert msTask1;
            // START ADDED BY Rohit for S-635394
            List <Milestone1_Task__c> milList = new List <Milestone1_Task__c>();
             milList.add(msTask1);
         //} Commented by Jasvinder for case: 00204418
        //Test.startTest();//commented for case 254740
         //Id BatchId = DataBase.executeBatch(new DueDateTaskUpdatedBatch(), 200);     
            DueDateTaskUpdatedBatch btch = new DueDateTaskUpdatedBatch();
            Database.QueryLocator ql = btch.start(null);
            btch.execute(null,milList);
            btch.Finish(null);
             // END ADDED BY Rohit for S-635394
        test.stopTest(); 
        } //Added by Jasvinder for case: 00204418 
     }
     
     static testMethod  void  testTaskScheduler(){
       Test.StartTest();
       DueDateTaskUpdatedBatchScheduler sh1 = new DueDateTaskUpdatedBatchScheduler();
       String sch = '0 0 6 * * ?';
       system.schedule('Test check', sch, sh1);
       Test.stopTest();
     }
    // create User
    static User createTestUser(Id profID, Id roleId, String fName, String lName) {
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            User tuser = new User(  firstname = fName,
                            lastName = lName,
                            email = uniqueName + '@test' + orgId + '.org',
                            Username = uniqueName + '@test' + orgId + '.org',
                            EmailEncodingKey = 'ISO-8859-1',
                            Alias = uniqueName.substring(18, 23),
                            TimeZoneSidKey = 'America/Los_Angeles',
                            LocaleSidKey = 'en_US',
                            LanguageLocaleKey = 'en_US',
                            ProfileId = profId,
                            UserRoleId = roleId
                            );
            insert tuser;                
            return tuser;
        }
}