force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Assessed_Executive__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TMG Deliverables (Assessments &amp; Coaching)</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>Date of scheduled assessment interview</description>
    <label>Interview Date</label>
    <summarizedField>Milestone1_Task__c.Scheduled_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Milestone1_Task__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Assessment Interview</value>
    </summaryFilterItems>
    <summaryForeignKey>Milestone1_Task__c.Project_Milestone__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Kickoff__c.field-meta.xml
<CustomField>
    <fullName>Kickoff__c</fullName>
    <inlineHelpText>Contract start date</inlineHelpText>
    <label>Kickoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Project_Wizard__c</fullName>
    <description>Automatically sets the Project Wizard for a deliverable based on the project. Used for creating PW as a related user for Deliverable work flows.</description>
    <formula>Project__r.Project_Wizard__r.Id</formula>
    <label>Project Wizard</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/TMG_Category__c.field-meta.xml
<CustomField>
    <fullName>TMG_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>TMG_Category__c.TMG_Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TMG_Category__c</referenceTo>
    <relationshipLabel>TMG Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Board_Dates__c.field-meta.xml
<CustomField>
    <fullName>Board_Dates__c</fullName>
    <description>List of Board meetings for the term of the engagement</description>
    <label>Board Dates</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
    <label>Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Kickoff__c.field-meta.xml
<CustomField>
    <fullName>Kickoff__c</fullName>
    <inlineHelpText>What date should this project start?</inlineHelpText>
    <label>Kickoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Project_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Project_Wizard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Wizard</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/TMG_Category__c.object-meta.xml
<CustomObject>
    <label>TMG Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Category__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Name__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Draft_Assessment__c</fullName>
    <label>Draft Assessment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Coaching_Plan__c.field-meta.xml
<CustomField>
    <fullName>Draft_Coaching_Plan__c</fullName>
    <label>Draft Coaching Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Final_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Final_Assessment__c</fullName>
    <description>Due date of final written assessment</description>
    <inlineHelpText>Due date of final written assessment</inlineHelpText>
    <label>Final Assessment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Kick_Off__c.field-meta.xml
<CustomField>
    <fullName>Kick_Off__c</fullName>
    <description>Start date</description>
    <inlineHelpText>Date of the first interview or reference</inlineHelpText>
    <label>Kick Off</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/TMG_Project__c.field-meta.xml
<CustomField>
    <fullName>TMG_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMG Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipLabel>TMG Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/recordTypes/Coaching.recordType-meta.xml
<RecordType>
    <fullName>Coaching</fullName>
    <active>true</active>
    <description>Follow-on coaching as part of the original assessment contract</description>
    <label>Coaching</label>
</RecordType>

force-app/main/default/objects/TMG_Category__c/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <description>Assessment Feedback Sessions</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/classes/TMGPProjectWizardController.cls
/****************************************************************
Name : TMGPProjectWizardController
Created Date : 2/18/15
Created by : Reena Acharya    
Description : Class for TMGPProjectWizard component.
****************************************************************/

global class TMGPProjectWizardController {

//Properties
public Id milestoneId {get;set;}
public Milestone1_Project__c milestone {get;set;}
public List<Milestone1_Milestone__c> participants ;//{get;set;}
public string dataCollection {get;set;}
public string draftAssessment{get;set;}
public string finalAssessment{get;set;}
public string draftCoaching {get;set;}
public string Debrief {get;set;}
public string projectLink {get;set;}


public List<Milestone1_Milestone__c> getparticipants(){
    loadData();     
    return participants ;
}
public TMG_Category__c category {get;set;}

 
// Data Collection  : Query TMG_Category__c records where TMG_Project__c = Milestone1_Project__c.Id and record type = “Data Collection" and show its due date (Due_Date__c) here. 
//Draft Assessment , Final Assessment, Draft Coaching Plan :
//          Query TMG_Category__c records where TMG_Project__c = Milestone1_Project__c.Id and record type = “Written Deliverables" and show its Draft_Assessment__c ,Final_Assessment__c and Draft_Coaching_Plan__c respectively.
//Debrief : Query TMG_Category__c records where TMG_Project__c = Milestone1_Project__c.Id and record type = "Feedback" or "Manager Debriefs" and show its due date (Due_Date__c) here (Which ever is earliest).        
// Pull all related Deliverable records to the project where the Assessed Executive field is not blank. Show the “Assessed Executive” and the “Interview Date” fields in Participants related section

public void loadData(){
        milestone = new Milestone1_Project__c ();
        List<Milestone1_Project__c> milestones = new List<Milestone1_Project__c >([Select id ,Name,Account__c,Account__r.Name, Client__c ,Client__r.Name, Kickoff__c,Deadline__c,Description__c,Board_Dates__c, Project_Wizard__c ,Project_Wizard__r.Name
                      from Milestone1_Project__c where id =: milestoneId]);
        if(milestones.size() > 0)
            milestone = milestones.get(0);

        participants = new List<Milestone1_Milestone__c>([Select id , Interview_Date__c ,Assessed_Executive__c,Assessed_Executive__r.Name from Milestone1_Milestone__c where Assessed_Executive__c != null and Project__c =: milestoneId and RecordType.Name = 'Data Collection']);
       
       List<TMG_Category__c> categories = new List<TMG_Category__c>([Select id,Due_Date__c from TMG_Category__c where TMG_Project__c =: milestoneId and recordType.Name = 'Data Collection' and Due_Date__c != null order by Due_Date__c asc limit 1]);                 
       if(categories.size() > 0)
           category.Due_Date__c = categories.get(0).Due_Date__c;
       
       categories = new List<TMG_Category__c>([Select id ,Draft_Assessment__c ,Final_Assessment__c ,Draft_Coaching_Plan__c 
                   from TMG_Category__c where TMG_Project__c =: milestoneId and recordType.Name = 'Written Deliverables' and Draft_Assessment__c  != null order by Draft_Assessment__c asc limit 1]);                 
       if(categories.size() > 0){
           category.Draft_Assessment__c = categories.get(0).Draft_Assessment__c;
           category.Final_Assessment__c = categories.get(0).Final_Assessment__c;
           category.Draft_Coaching_Plan__c= categories.get(0).Draft_Coaching_Plan__c ;
       }
       categories = new List<TMG_Category__c>([Select id,Due_Date__c from TMG_Category__c where TMG_Project__c =: milestoneId and (recordType.Name ='Feedback' or recordType.Name = 'Manager Debriefs') order by Due_Date__c asc limit 1]);                 
       if(categories.size() > 0)
           category.Kick_Off__c = categories.get(0).Due_Date__c ;
           
       projectLink = URL.getSalesforceBaseUrl().toExternalForm() + '/'+ milestoneId ;
}
        
//Constructor       
public TMGPProjectWizardController() {
    category = new TMG_Category__c();
     system.debug('===milestoneId  ==='+ milestoneId  );
    if(milestoneId  != null){   
        loadData();
    }
}


}