force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>This is the alias for a milestone.</description>
    <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
    <label>Deliverable Alias</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>TMG Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task.</inlineHelpText>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Email_GUID__c.field-meta.xml
<CustomField>
    <fullName>Email_GUID__c</fullName>
    <description>This field is used to track Email for a reply to email chain.</description>
    <externalId>true</externalId>
    <label>Email GUID</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DueDateTaskDetailsExtensionTest.cls
/*********************************************************************************
Name : Jyotirmaya Rath
Created By : Appirio  
Created Date : 03 Nov 2015
Purpose : Test Class For DueDateTaskDetailsExtension
 *********************************************************************************/
@isTest
public class DueDateTaskDetailsExtensionTest {
    @isTest public static void testTaskDueDate(){
        String taskName = 'Unit Test Email Notes 123';
        Test.startTest(); //added for case 254740      
            Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProject('proj');
            insert proj;

            Milestone1_Milestone__c ms1 = Milestone1_Test_Utility.sampleMilestone(proj.Id, null, 'ms1');
            ms1.Alias__c = 'unit_test';
            insert ms1;

            Milestone1_Task__c msTask1 = Milestone1_Test_Utility.sampleTask(ms1.Id);
            msTask1.Name = taskName;
       
            Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' limit 1]; 
            User u = createTestUser(p.Id,'test','user1');
            msTask1.Assigned_To__c = u.id ;
      //      msTask1.Email_GUID__c = 'UNIQUE_TEST123' + Date.today();
            insert msTask1;
        //Test.startTest();//commented for case 254740       
           PageReference pageRef = Page.DueDateTaskdetails;                        
           Test.setCurrentPage(pageRef);
           ApexPages.currentPage().getParameters().put('id', msTask1.id);  
           ApexPages.currentPage().getParameters().put('ans', 'yes');
           DueDateTaskDetailsExtension Ext = new DueDateTaskDetailsExtension(new ApexPages.StandardController(msTask1));
                                          
           Ext.answerYes();
         ApexPages.currentPage().getParameters().put('ans', 'no');
        Ext = new DueDateTaskDetailsExtension(new ApexPages.StandardController(msTask1));
        Ext.answerYes();
        ext.submitTask();
           
           Test.stopTest();
    }
    public static User createTestUser(Id profID, String fName, String lName) {
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            User tuser = new User(  firstname = fName,
                            lastName = lName,
                            email = uniqueName + '@test' + orgId + '.org',
                            Username = uniqueName + '@test' + orgId + '.org',
                            EmailEncodingKey = 'ISO-8859-1',
                            Alias = uniqueName.substring(18, 23),
                            TimeZoneSidKey = 'America/Los_Angeles',
                            LocaleSidKey = 'en_US',
                            LanguageLocaleKey = 'en_US',
                            ProfileId = profId
                            );
            return tuser;
        }
}