force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Expense_Budget__c.field-meta.xml
<CustomField>
    <fullName>Expense_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The expense budget for the milestone.</inlineHelpText>
    <label>Deliverable Expense Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Hours_Budget__c.field-meta.xml
<CustomField>
    <fullName>Hours_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The hours budget for the milestone.</inlineHelpText>
    <label>Deliverable Hours Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Interview Approved</fullName>
            </value>
            <value>
                <fullName>Referencing</fullName>
            </value>
            <value>
                <fullName>Writing</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
    <label>Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <inlineHelpText>The current status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>ADMIN ONLY</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved / Planning (95%)</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-billable</fullName>
                <isActive>false</isActive>
                <label>Non-billable</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <isActive>false</isActive>
                <label>Planning</label>
            </value>
            <value>
                <fullName>To Be Submitted</fullName>
                <isActive>false</isActive>
                <label>To Be Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>TMG Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task.</inlineHelpText>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <inlineHelpText>Classify this task as appropriate for your use.</inlineHelpText>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ad Hoc</fullName>
            </value>
            <value>
                <fullName>Defect</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
    <label>Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The general description of the task. For example, what is the purpose of the task.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>Task Target Due Date</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Estimated_Expense__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Expense__c</fullName>
    <inlineHelpText>The estimated amount of expenses which will be incurred during the task.</inlineHelpText>
    <label>Estimated Expense</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/First_Chair_User__c.field-meta.xml
<CustomField>
    <fullName>First_Chair_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Chair</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Last_Email_Received__c.field-meta.xml
<CustomField>
    <fullName>Last_Email_Received__c</fullName>
    <description>Date Time the last email was sent to this task.</description>
    <inlineHelpText>The date the last email was attached to this task. A task can be created via an email, and additional emails can be attached to the task in the notes section.</inlineHelpText>
    <label>Last Email Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>This is the priority of the task. 0,1,2,3 or 4.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <color>#000000</color>
                <label>Low</label>
            </value>
            <value>
                <fullName>High</fullName>
                <color>#FF0000</color>
                <label>High</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
    <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
    <label>Project Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Deliverable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone1_Milestone__c.Complete__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Task Projected Start Date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Task_Stage__c.field-meta.xml
<CustomField>
    <fullName>Task_Stage__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <inlineHelpText>Where is this task on the road to completion?</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assigned</fullName>
            </value>
            <value>
                <fullName>To Be Scheduled</fullName>
            </value>
            <value>
                <fullName>Client Contacted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled by TMG</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>TBR (To Be Rescheduled)</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>To Be Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Confirmed</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Incomplete (Calendar Conflicts)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Batch_NotifyForCoachingTaskDues.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=false)
private class Test_Batch_NotifyForCoachingTaskDues {
/**
 *  Purpose         :   This test class is for Batch_NotifyForCoachingTaskDues class.
 *
 *  Created By      :   Padmesh Soni (Appirio Offshore)
 *
 *  Created Date    :   12/4/2015
 *
 *  Current Version :   V1.1
 *
 *  Revision Log    :   V1.0 - Created - S-358685
 *                      V1.1 - Modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
 *
 *  Coverage        :   V1.0 - 99%
 *                      V1.1 - 99%
 **/
    
    //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
    //query result of current user
    public static User currentUser = [SELECT Id FROM User WHERE Id =: Userinfo.getUserId()];
        
    static testMethod void testNotificationFirst() {
        
        Schema.DescribeSObjectResult taskObj = Milestone1_Task__c.sObjectType.getDescribe();
        Map<String,Schema.recordTypeInfo> mapRecordsType = taskObj.getRecordTypeInfosByName();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        //Queyr result of current user
        UserRole role = new UserRole(name = 'Miles Group');
        
        //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
        //Fix the context to pervent Mixed DML operation exception
        System.runAs(currentUser) {
            insert role;       
        }
        
        List<User> users = new List<User>();
        users.add(new User(alias = 'jsmtih', email='jsmith@acme.com', emailencodingkey='UTF-8', lastname='Smith', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        users.add(new User(alias = 'jsmti', email='jsmit1h@acme.com', emailencodingkey='UTF-8', lastname='Smith1', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        
        //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
        //Fix the context to pervent Mixed DML operation exception
        System.runAs(currentUser) {
        System.debug('line ### 69');
            insert users;
        }
        
        // Create a poject
        
        List<Milestone1_Project__c> projects = new List<Milestone1_Project__c>();
        projects.add(new Milestone1_Project__c(Name = 'Test Project', Status__c = 'Submitted'));
        insert projects;
    
        // Create a Deliverable
        List<Milestone1_Milestone__c> deliverables = new List<Milestone1_Milestone__c>();
        deliverables.add(new Milestone1_Milestone__c(Name = 'Test'  + Datetime.now().getTime(), Project__c = projects[0].id, Complete__c = false,
                                                            Description__c = 'Description for Test 1',
                                                            Expense_Budget__c = Math.floor(Math.random() * 50000 * 100) / 100, 
                                                            Hours_Budget__c = Math.floor(Math.random() * 500 * 100) / 100,
                                                            Status__c = 'approved'));
        System.debug('line ### 84');
        insert deliverables;
        
        //Create Coaching Tasks
        List<Milestone1_Task__c> coachingTasks = new List<Milestone1_Task__c>();
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, RecordTypeId = mapRecordsType.get('All Functions').getRecordTypeId(), //Updated by Jasvinder for case: 00204418
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, RecordTypeId = mapRecordsType.get('All Functions').getRecordTypeId(), //Updated by Jasvinder for case: 00204418
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, RecordTypeId = mapRecordsType.get('All Functions').getRecordTypeId(),  //Updated by Jasvinder for case: 00204418
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, RecordTypeId = mapRecordsType.get('All Functions').getRecordTypeId(),  //Updated by Jasvinder for case: 00204418
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, RecordTypeId = mapRecordsType.get('All Functions').getRecordTypeId(), //Updated by Jasvinder for case: 00204418
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        
        insert coachingTasks;
        
        //Test starts here
        Test.startTest();
        
        //Batch isntances
        Batch_NotifyForCoachingTaskDues bc = new Batch_NotifyForCoachingTaskDues(1);
        
        //Execute the batch
        Database.executeBatch(bc, 200);
        
 
        //Test stops here
        Test.stopTest();
    }
    
   //Below method added by Shreya for case#00273279 Start
    public static Boolean runningInASandbox() {

            Boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        
        return runningInASandbox;
        }
    //Above method added by Shreya for case#00273279 End
    
    // JesseB Commenting out this method
    static testMethod void testNotificationSecond() {
        
        Schema.DescribeSObjectResult taskObj = Milestone1_Task__c.sObjectType.getDescribe();
        Map<String,Schema.recordTypeInfo> mapTaskRecordsType = taskObj.getRecordTypeInfosByName();
        Schema.DescribeSObjectResult deliverableObj = Milestone1_Milestone__c.sObjectType.getDescribe();
        Map<String,Schema.recordTypeInfo> mapDeliverableRecordsType = deliverableObj.getRecordTypeInfosByName();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        Profile p1;
        
        //If condition and Query added by Shreya for case#00273279
        if(runningInASandbox()){
        p1 = [SELECT Id FROM Profile WHERE Name='Miles Group Platform User']; 
        }
        //Else condition added by Shreya for case#00273279
        else{
        p1 = [SELECT Id FROM Profile WHERE Name='Miles Group Admin User'];//Code Modified By Gunjan Sharma for case - 00269646
        }
        UserRole role = new UserRole(name = 'Miles Group');
        
        //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
        //Fix the context to pervent Mixed DML operation exception
        System.runAs(currentUser) {
            insert role;       
        } 
        
        List<User> users = new List<User>();
        users.add(new User(alias = 'jsmtih', email='jsmith@acme.com', emailencodingkey='UTF-8', lastname='Smith', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        users.add(new User(alias = 'jsmti', email='jsmit1h@acme.com', emailencodingkey='UTF-8', lastname='Smith1', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        users.add(new User(alias = 'lBrown', email='lBrown@acme.com', emailencodingkey='UTF-8', firstname='LaKenya',lastname='Brown', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p1.Id, timezonesidkey='America/Los_Angeles', username='USERNAME_JAN_STOE'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
        //Fix the context to pervent Mixed DML operation exception
        System.runAs(currentUser) {
            insert users;
        }
        
        // Create a poject
        List<Milestone1_Project__c> projects = new List<Milestone1_Project__c>();
        projects.add(new Milestone1_Project__c(Name = 'Test Project', Status__c = 'Active'));//Modified By Saurabh S-640524
        insert projects;
    
        // Create a Deliverable
        List<Milestone1_Milestone__c> deliverables = new List<Milestone1_Milestone__c>();
        deliverables.add(new Milestone1_Milestone__c(Name = 'Test'  + Datetime.now().getTime(), Project__c = projects[0].id, Complete__c = false,
                                                            Description__c = 'Description for Test 1',
                                                            Expense_Budget__c = Math.floor(Math.random() * 50000 * 100) / 100, 
                                                            Hours_Budget__c = Math.floor(Math.random() * 500 * 100) / 100, Deadline__c = Date.today().addDays(-30),
                                                            RecordTypeId = mapDeliverableRecordsType.get('Executive Coaching').getRecordTypeId(),
                                                            Status__c = 'approved'));
        
        insert deliverables;
        
        //Create Coaching Tasks
        List<Milestone1_Task__c> coachingTasks = new List<Milestone1_Task__c>();
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, 
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(),
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(),
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(), 
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(), 
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(), 
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_TO_BE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        
        insert coachingTasks;
        
        //Test starts here
        Test.startTest();
        
        //Batch isntances
        Batch_NotifyForCoachingTaskDues bc = new Batch_NotifyForCoachingTaskDues(2);
        
        //Execute the batch
        Database.executeBatch(bc, 200);
        
        //Test stops here
        Test.stopTest();
    }
     //JesseB END */
    static testMethod void testNotificationThird() {
        
        Schema.DescribeSObjectResult taskObj = Milestone1_Task__c.sObjectType.getDescribe();
        Map<String,Schema.recordTypeInfo> mapTaskRecordsType = taskObj.getRecordTypeInfosByName();
        Schema.DescribeSObjectResult deliverableObj = Milestone1_Milestone__c.sObjectType.getDescribe();
        Map<String,Schema.recordTypeInfo> mapDeliverableRecordsType = deliverableObj.getRecordTypeInfosByName();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        UserRole role = new UserRole(name = 'Miles Group');
        
        //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
        //Fix the context to pervent Mixed DML operation exception
        System.runAs(currentUser) {
            insert role;       
        }
        
        List<User> users = new List<User>();
        users.add(new User(alias = 'jsmtih', email='jsmith@acme.com', emailencodingkey='UTF-8', lastname='Smith', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        users.add(new User(alias = 'jsmti', email='jsmit1h@acme.com', emailencodingkey='UTF-8', lastname='Smith1', languagelocalekey='en_US', localesidkey='en_US', 
                            profileid = p.Id, timezonesidkey='America/Los_Angeles', username='test'+ Math.random()+'@acme.com', UserRoleId = role.Id));
        
        //Code modified - Ankush Bhatia (Appirio Offshore - 12/8/2015) - Case #: 00143291
        //Fix the context to pervent Mixed DML operation exception
        System.runAs(currentUser) {
            insert users;
        }
        
        // Create a poject
        List<Milestone1_Project__c> projects = new List<Milestone1_Project__c>();
        projects.add(new Milestone1_Project__c(Name = 'Test Project', Status__c = 'Submitted'));
        insert projects;
    
        // Create a Deliverable
        List<Milestone1_Milestone__c> deliverables = new List<Milestone1_Milestone__c>();
        deliverables.add(new Milestone1_Milestone__c(Name = 'Test'  + Datetime.now().getTime(), Project__c = projects[0].id, Complete__c = false,
                                                            Description__c = 'Description for Test 1',
                                                            Expense_Budget__c = Math.floor(Math.random() * 50000 * 100) / 100, 
                                                            Hours_Budget__c = Math.floor(Math.random() * 500 * 100) / 100, Deadline__c = Date.today().addDays(-30),
                                                            RecordTypeId = mapDeliverableRecordsType.get('Executive Coaching').getRecordTypeId(),
                                                            Status__c = 'approved'));
        
        insert deliverables;
        System.debug('line ### 286'+deliverables);
        //Create Coaching Tasks
        List<Milestone1_Task__c> coachingTasks = new List<Milestone1_Task__c>();
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id, 
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(),
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', Scheduled_Date__c = Date.today().addDays(-1),
                                                    Task_Stage__c = Label.TASK_STAGE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(),
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', Scheduled_Date__c = Date.today().addDays(-1), 
                                                    Task_Stage__c = Label.TASK_STAGE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(), 
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', Scheduled_Date__c = Date.today().addDays(-1), 
                                                    Task_Stage__c = Label.TASK_STAGE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(), 
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', Scheduled_Date__c = Date.today().addDays(-1), 
                                                    Task_Stage__c = Label.TASK_STAGE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        coachingTasks.add(new Milestone1_Task__c(Project_Milestone__c = deliverables[0].Id, Assigned_To__c = users[0].Id,
                                                    RecordTypeId = mapTaskRecordsType.get('Coaching Session').getRecordTypeId(), 
                                                    Name = 'MS ' + deliverables[0].Id + ' task ' + Datetime.now().getTime(), 
                                                    Complete__c = true, Description__c   = 'test description ' + Datetime.now().getTime(), 
                                                    Start_Date__c   = Date.today().addDays(1), Due_Date__c   = Date.today().addDays(-25), Scheduled_Date__c = Date.today().addDays(-1), 
                                                    Estimated_Expense__c = 100.00, Estimated_Hours__c = 110.00, Priority__c = '0', 
                                                    Task_Stage__c = Label.TASK_STAGE_SCHEDULED, Class__c = 'Ad Hoc', First_Chair_User__c = users[1].Id,
                                                    Last_Email_Received__c = Datetime.now()));
        
        insert coachingTasks; 
        Test.starttest();//Bhagya case 00257645
        for(Milestone1_Task__c task : coachingTasks) {
            
            task.Due_Date__c = Date.today();
        }
        
        update coachingTasks; //commented by Shreya for case#00273279
        //Test.stoptest();//Bhagya case 00257645
        //Test starts here
        //Test.startTest();
        
        //Batch isntances
        Batch_NotifyForCoachingTaskDues bc = new Batch_NotifyForCoachingTaskDues(3);
        
        //Execute the batch
       // Database.executeBatch(bc, 200); //case 00257645
         Database.executeBatch(bc, 20);
        //Test stops here
        Test.stopTest(); //modified by Himanshu Baghmar for Case #00266951
    }
}