force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>This is the alias for a milestone.</description>
    <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
    <label>Deliverable Alias</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Main_Project_Debrief__c.field-meta.xml
<CustomField>
    <fullName>Main_Project_Debrief__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Key Stakeholder or Group debrief task for the project</description>
    <inlineHelpText>The Key Stakeholder or Group debrief task for the project</inlineHelpText>
    <label>Main Project Debrief</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone1_Task__c.Project_Milestone__r.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Milestone1_Task__c.Complete__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Milestone1_Task__c</referenceTo>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/recordTypes/Stakeholder_Debrief.recordType-meta.xml
<RecordType>
    <fullName>Stakeholder_Debrief</fullName>
    <active>true</active>
    <description>Use for all Stakeholder/Manager alignments &amp; debriefs</description>
    <label>Stakeholder Debrief</label>
</RecordType>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>TMG Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task.</inlineHelpText>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
    <label>Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/First_Chair_User__c.field-meta.xml
<CustomField>
    <fullName>First_Chair_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Chair</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Deliverable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone1_Milestone__c.Complete__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Second_Chair_User__c.field-meta.xml
<CustomField>
    <fullName>Second_Chair_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Second Chair</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Task_Stage__c.field-meta.xml
<CustomField>
    <fullName>Task_Stage__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <inlineHelpText>Where is this task on the road to completion?</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assigned</fullName>
            </value>
            <value>
                <fullName>To Be Scheduled</fullName>
            </value>
            <value>
                <fullName>Client Contacted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled by TMG</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>TBR (To Be Rescheduled)</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>To Be Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Confirmed</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Incomplete (Calendar Conflicts)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/recordTypes/Stakeholder_Debrief.recordType-meta.xml
<RecordType>
    <fullName>Stakeholder_Debrief</fullName>
    <active>true</active>
    <label>Stakeholder Debrief</label>
</RecordType>

force-app/main/default/classes/DueDateTaskDetailsBatchTest.cls
/*********************************************************************************
Name : Jyotirmaya Rath
Created By : Appirio  
Created Date : 03 Nov 2015
Updated: 15 Jan 2018 JesseB Case 00215311
Purpose : Test Class for  DueDateTaskDetailsBatchTest
*********************************************************************************/
@isTest(SeeAllData=true) //Lokesh Korani Case 00248710
public class DueDateTaskDetailsBatchTest {
     @isTest (SeeAllData=true)//Lokesh Korani Case 00248710
    public static void testTaskDueDate(){
         String taskName = 'Unit Test Email Notes 123';
         
            Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProject('proj');
            insert proj;
            Milestone1_Milestone__c ms1 = Milestone1_Test_Utility.sampleMilestone(proj.Id, null, 'ms1');
            ms1.Alias__c = 'unit_test';
            //test.startTest();//added for case 254740
            insert ms1;
            //Start Lokesh Korani Case 00248710
            List<Milestone1_Milestone__c> idLst = [Select id from Milestone1_Milestone__c  WHERE Complete__c = false and Total_Open_Tasks__c = 2 and
                                                   Main_Project_Debrief__r.Project_Milestone__r.RecordType.DeveloperName = null 
                                                   AND RecordType.DeveloperName = 'Stakeholder_Debrief'];
            //End Lokesh Korani Case 00248710
            Milestone1_Task__c msTask1 = Milestone1_Test_Utility.sampleTask(ms1.Id);
            msTask1.Name = taskName;
            msTask1.RecordType = [SELECT id FROM RecordType WHERE Name = 'Coaching Session'];
            UserRole r = [SELECT Id FROM UserRole WHERE Name='Miles Group' limit 1];
            Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' limit 1];
            User u = createTestUser(p.Id,r.Id,'test','user1');
         //Start Lokesh Korani Case 00248710
             User runUser=[Select id from User where Name='Stephen Miles'];
            System.runAs(runUser){
            msTask1.Assigned_To__c = runUser.id ;
                msTask1.Complete__c = True;
            msTask1.Project_Milestone__c = idLst.get(0).id;
            msTask1.Task_Stage__c  = 'Scheduled';
            msTask1.Scheduled_Date__c  = System.today().addDays(-7);
            msTask1.First_Chair_User__c = runUser.id;
            msTask1.Second_Chair_User__c = runUser.id;
            insert msTask1;
         }          
         //End Lokesh Korani Case 00248710
         //test.startTest();//commented for case -254740
         Id BatchId = DataBase.executeBatch(new DueDateTaskDetailsBatch(), 200);
         
         //test.stopTest();

       //  test.startTest();    
     }
    // create User
    public static User createTestUser(Id profID, Id roleId, String fName, String lName) {
            String orgId = UserInfo.getOrganizationId();
            String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
            Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
            String uniqueName = orgId + dateString + randomInt;
            User tuser = new User(  firstname = fName,
                            lastName = lName,
                            email = uniqueName + '@test' + orgId + '.org',
                            Username = uniqueName + '@test' + orgId + '.org',
                            EmailEncodingKey = 'ISO-8859-1',
                            Alias = uniqueName.substring(18, 23),
                            TimeZoneSidKey = 'America/Los_Angeles',
                            LocaleSidKey = 'en_US',
                            LanguageLocaleKey = 'en_US',
                            ProfileId = profId,
                            UserRoleId = roleId
                            );
            // START JWEBB C-00228360 05/14/2018
            // insert tuser;
            // END JWEBB C-00228360 05/14/2018
            return tuser;
        }
}