force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Assessed_Executive__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TMG Deliverables (Assessments &amp; Coaching)</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <description>Date of scheduled assessment interview</description>
    <label>Interview Date</label>
    <summarizedField>Milestone1_Task__c.Scheduled_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Milestone1_Task__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Assessment Interview</value>
    </summaryFilterItems>
    <summaryForeignKey>Milestone1_Task__c.Project_Milestone__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Kickoff__c.field-meta.xml
<CustomField>
    <fullName>Kickoff__c</fullName>
    <inlineHelpText>Contract start date</inlineHelpText>
    <label>Kickoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Project_Wizard__c</fullName>
    <description>Automatically sets the Project Wizard for a deliverable based on the project. Used for creating PW as a related user for Deliverable work flows.</description>
    <formula>Project__r.Project_Wizard__r.Id</formula>
    <label>Project Wizard</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Interview Approved</fullName>
            </value>
            <value>
                <fullName>Referencing</fullName>
            </value>
            <value>
                <fullName>Writing</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/TMG_Category__c.field-meta.xml
<CustomField>
    <fullName>TMG_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>TMG_Category__c.TMG_Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TMG_Category__c</referenceTo>
    <relationshipLabel>TMG Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Board_Dates__c.field-meta.xml
<CustomField>
    <fullName>Board_Dates__c</fullName>
    <description>List of Board meetings for the term of the engagement</description>
    <label>Board Dates</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
    <label>Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Kickoff__c.field-meta.xml
<CustomField>
    <fullName>Kickoff__c</fullName>
    <inlineHelpText>What date should this project start?</inlineHelpText>
    <label>Kickoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Project_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Project_Wizard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Wizard</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <inlineHelpText>The current status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>ADMIN ONLY</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved / Planning (95%)</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-billable</fullName>
                <isActive>false</isActive>
                <label>Non-billable</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <isActive>false</isActive>
                <label>Planning</label>
            </value>
            <value>
                <fullName>To Be Submitted</fullName>
                <isActive>false</isActive>
                <label>To Be Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TMG_Category__c/TMG_Category__c.object-meta.xml
<CustomObject>
    <label>TMG Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Category__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Name__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Draft_Assessment__c</fullName>
    <label>Draft Assessment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Coaching_Plan__c.field-meta.xml
<CustomField>
    <fullName>Draft_Coaching_Plan__c</fullName>
    <label>Draft Coaching Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Key_Selection_Criteria_Revise_St__c.field-meta.xml
<CustomField>
    <fullName>Draft_Key_Selection_Criteria_Revise_St__c</fullName>
    <description>Deadline for 1st draft of Key Selection Criteria and/or revised Strawman</description>
    <inlineHelpText>Deadline for 1st draft of Key Selection Criteria and/or revised Strawman</inlineHelpText>
    <label>Draft Key Selection Criteria / Revise St</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Process_Document__c.field-meta.xml
<CustomField>
    <fullName>Draft_Process_Document__c</fullName>
    <description>Deadline for 1st draft of process document</description>
    <inlineHelpText>Deadline for 1st draft of process document</inlineHelpText>
    <label>Draft Process Document</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Questionnaire_Strawman__c.field-meta.xml
<CustomField>
    <fullName>Draft_Questionnaire_Strawman__c</fullName>
    <description>Deadline for 1st draft of questionnaire and/or Strawman</description>
    <inlineHelpText>Deadline for 1st draft of questionnaire and/or Strawman</inlineHelpText>
    <label>Draft Questionnaire / Strawman</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Final_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Final_Assessment__c</fullName>
    <description>Due date of final written assessment</description>
    <inlineHelpText>Due date of final written assessment</inlineHelpText>
    <label>Final Assessment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Final_Key_Selection_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Final_Key_Selection_Criteria__c</fullName>
    <description>Deadline for final Key Selection Criteria or offsite presentation</description>
    <inlineHelpText>Deadline for final Key Selection Criteria or offsite presentation</inlineHelpText>
    <label>Key Criteria / Offsite Presentation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Kick_Off__c.field-meta.xml
<CustomField>
    <fullName>Kick_Off__c</fullName>
    <description>Start date</description>
    <inlineHelpText>Date of the first interview or reference</inlineHelpText>
    <label>Kick Off</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/TMG_Project__c.field-meta.xml
<CustomField>
    <fullName>TMG_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMG Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipLabel>TMG Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <description>Assessment Feedback Sessions</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/classes/TMGPProjectWizardCEOSuccessController.cls
global class TMGPProjectWizardCEOSuccessController {
	global string milestoneId{get; set;}
	global Milestone1_Project__c milestone{
		get{
			Milestone1_Project__c milestone = new Milestone1_Project__c();
			if(milestoneId != null){
				List<Milestone1_Project__c> milestones = new List<Milestone1_Project__c>([Select Id, Name, RecordType.Name, Project_Wizard__r.Name, Status__c, Account__r.Name, Kickoff__c, Client__r.Name, Deadline__c, Description__c, Board_Dates__c from Milestone1_Project__c where Id=:milestoneId AND RecordType.Name = 'CEO Succession' Limit 1]);
				if(milestones.size()>0){
					milestone = milestones.get(0);
				}
			}
			return milestone;
		}
		set;
	}
	global TMG_Category__c category{
		get{
			TMG_Category__c category = new TMG_Category__c();
			if(milestoneId != null){
			   List<TMG_Category__c> categories = new List<TMG_Category__c>([Select id,Due_Date__c from TMG_Category__c where TMG_Project__c =: milestoneId and recordType.Name = 'Data Collection' and Due_Date__c != null order by Due_Date__c asc limit 1]);                 
		       if(categories.size() > 0)
		           category.Due_Date__c = categories.get(0).Due_Date__c;
		       categories = new List<TMG_Category__c>([Select id ,Draft_Assessment__c ,Final_Assessment__c ,Draft_Coaching_Plan__c from TMG_Category__c where TMG_Project__c =: milestoneId and recordType.Name = 'Written Deliverables' and Draft_Assessment__c  != null order by Draft_Assessment__c asc limit 1]);                 
		       if(categories.size() > 0){
		           category.Draft_Assessment__c = categories.get(0).Draft_Assessment__c;
		           category.Final_Assessment__c = categories.get(0).Final_Assessment__c;
		           category.Draft_Coaching_Plan__c= categories.get(0).Draft_Coaching_Plan__c ;
		       }
		       categories = new List<TMG_Category__c>([Select id,Due_Date__c from TMG_Category__c where TMG_Project__c =: milestoneId and (recordType.Name ='Feedback' or recordType.Name = 'Manager Debriefs') order by Due_Date__c asc limit 1]);                 
		       if(categories.size() > 0)
		           category.Kick_Off__c = categories.get(0).Due_Date__c ;
	           categories = new List<TMG_Category__c>([Select Draft_Process_Document__c, Draft_Questionnaire_Strawman__c, Draft_Key_Selection_Criteria_Revise_St__c, Final_Key_Selection_Criteria__c from TMG_Category__c where TMG_Project__c =: milestoneId and recordType.Name ='S&E Profile' order by Due_Date__c asc limit 1]);
			   if(categories.size() > 0){
			   		category.Draft_Process_Document__c = categories.get(0).Draft_Process_Document__c;
			   		category.Draft_Questionnaire_Strawman__c = categories.get(0).Draft_Questionnaire_Strawman__c;
			   		category.Draft_Key_Selection_Criteria_Revise_St__c = categories.get(0).Draft_Key_Selection_Criteria_Revise_St__c;
			   		category.Final_Key_Selection_Criteria__c = categories.get(0).Final_Key_Selection_Criteria__c;
			   }
			}
			return category;
		}
		set;
	}
	global List<Milestone1_Milestone__c> participants{
		get{
			List<Milestone1_Milestone__c> participants = new List<Milestone1_Milestone__c>();
			if(milestoneId != null){
				participants = new List<Milestone1_Milestone__c>([Select id , Interview_Date__c ,Assessed_Executive__c,Assessed_Executive__r.Name from Milestone1_Milestone__c where Assessed_Executive__c != null and Project__c =: milestoneId and RecordType.Name = 'Data Collection']);
			}
			return participants;
		}
		set;
	}
	global string projectLink{
		get{
			string projectLink = '';
			if(milestoneId != null){
				projectLink = URL.getSalesforceBaseUrl().toExternalForm() + '/'+ milestoneId ;
			}
			return projectLink;
		}
	}
	global Milestone1_Milestone__c inteviewDeliverable{
		get{
			Milestone1_Milestone__c inteviewDeliverable = new Milestone1_Milestone__c();
			if(milestoneId != null){
				List<Milestone1_Milestone__c> deliverables = new List<Milestone1_Milestone__c>([Select Id, Deadline__c from Milestone1_Milestone__c where Project__c = :milestoneId AND RecordType.Name = 'Interview' order by Deadline__c asc limit 1 ]);
				if(deliverables.size()>0){
					inteviewDeliverable = deliverables.get(0);
				}
			}
			return inteviewDeliverable;
		}
		set;
	}
	global Milestone1_Milestone__c debriefDeliverable{
		get{
			Milestone1_Milestone__c debriefDeliverable = new Milestone1_Milestone__c();
			if(milestoneId != null){
				List<Milestone1_Milestone__c> deliverables = new List<Milestone1_Milestone__c>([Select Id, Deadline__c from Milestone1_Milestone__c where Project__c = :milestoneId AND RecordType.Name = 'Stakeholder Debrief' order by Deadline__c asc limit 1 ]);
				if(deliverables.size()>0){
					debriefDeliverable = deliverables.get(0);
				}
			}
			return debriefDeliverable;
		}
		set;
	}
}