force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Interview Approved</fullName>
            </value>
            <value>
                <fullName>Referencing</fullName>
            </value>
            <value>
                <fullName>Writing</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/TMG_Category__c.field-meta.xml
<CustomField>
    <fullName>TMG_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>TMG_Category__c.TMG_Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TMG_Category__c</referenceTo>
    <relationshipLabel>TMG Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <inlineHelpText>The current status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>ADMIN ONLY</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved / Planning (95%)</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-billable</fullName>
                <isActive>false</isActive>
                <label>Non-billable</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <isActive>false</isActive>
                <label>Planning</label>
            </value>
            <value>
                <fullName>To Be Submitted</fullName>
                <isActive>false</isActive>
                <label>To Be Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TMG_Category__c/TMG_Category__c.object-meta.xml
<CustomObject>
    <label>TMG Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Category__c/fields/Draft_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Draft_Assessment__c</fullName>
    <label>Draft Assessment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/TMG_Project__c.field-meta.xml
<CustomField>
    <fullName>TMG_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMG Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipLabel>TMG Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <description>Assessment Feedback Sessions</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/classes/TMGPProjectWizardCEOSuccessController_TC.cls
/**********************************************
/* Name : TMGPProjectWizardCEOSuccessController_TC
/* Created By : Shubham
/* Case : 00138614
/*********************************************/
@isTest
private class TMGPProjectWizardCEOSuccessController_TC {

    static testMethod void myUnitTest() {
        RecordType RecType1 = [select Id from RecordType where SobjectType = 'Milestone1_Project__c' AND Name = 'CEO Succession'];
        Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProjectActive('SampleProject');
        //SSANDHU 00224743 START
        proj.Status__c = 'Submitted'; 
        //SSANDHU 00224743 END
        proj.RecordTypeId = RecType1.Id;
        insert proj;
        Milestone1_Milestone__c parentMilestone = Milestone1_Test_Utility.sampleMilestone(proj);
        Milestone1_Milestone__c milestone = Milestone1_Test_Utility.sampleMilestone(proj.Id, parentMilestone.Id, 'SampleMilestone');
        insert milestone;
        
        Test.startTest();
        TMGPProjectWizardCEOSuccessController con = new TMGPProjectWizardCEOSuccessController();
        con.milestoneId = proj.Id;
        Milestone1_Project__c proj1 = con.milestone;
        List<Milestone1_Milestone__c> participants = con.participants;
        string projectLink = con.projectLink;
        Milestone1_Milestone__c inteviewDeliverable = con.inteviewDeliverable;
        Milestone1_Milestone__c debriefDeliverable = con.debriefDeliverable;
        
        RecordType RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'Data Collection'];
        TMG_Category__c cat = new TMG_Category__c();
        cat.Name = 'Billing';
        cat.TMG_Project__c = proj.Id;
        cat.Due_Date__c = Date.today().addDays(14);
        cat.RecordTypeId = RecType.Id;
        insert cat;
        
        RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'Written Deliverables'];
        TMG_Category__c cat1 = new TMG_Category__c();
        cat1.Name = 'Billing';
        cat1.TMG_Project__c = proj.Id;
        cat1.Due_Date__c = Date.today().addDays(14);
        cat1.RecordTypeId = RecType.Id;
        cat1.Draft_Assessment__c = Date.today().addDays(1);
        insert cat1;
        
        RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'Feedback'];
        TMG_Category__c cat2 = new TMG_Category__c();
        cat2.Name = 'Billing';
        cat2.TMG_Project__c = proj.Id;
        cat2.Due_Date__c = Date.today().addDays(14);
        cat2.RecordTypeId = RecType.Id;
        insert cat2;
        
        RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'S&E Profile'];
        TMG_Category__c cat3 = new TMG_Category__c();
        cat3.Name = 'Billing';
        cat3.TMG_Project__c = proj.Id;
        cat3.Due_Date__c = Date.today().addDays(14);
        cat3.RecordTypeId = RecType.Id;
        insert cat3;
        
        TMG_Category__c cat10 = con.category;
        
        Test.stopTest();
    }
    
    // added for the story #S-362576 #START
    static testMethod void myUnitTest1() {
        
        RecordType RecType1 = [select Id from RecordType where SobjectType = 'Milestone1_Project__c' AND Name = 'CEO Succession'];
        Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProjectActive('SampleProject');
        proj.RecordTypeId = RecType1.Id;
        //SSANDHU 00224743 START
        proj.Status__c = 'Submitted';
        //SSANDHU 00224743 END  
        insert proj;
        Milestone1_Milestone__c parentMilestone = Milestone1_Test_Utility.sampleMilestone(proj);
        
        TMGPProjectWizardCEOSuccessController con = new TMGPProjectWizardCEOSuccessController();
        con.milestoneId = proj.Id;
        Milestone1_Project__c proj1 = con.milestone;
        List<Milestone1_Milestone__c> participants = con.participants;
        string projectLink = con.projectLink;
        Milestone1_Milestone__c inteviewDeliverable = con.inteviewDeliverable;
        Milestone1_Milestone__c debriefDeliverable = con.debriefDeliverable;
        
        RecordType RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'Data Collection'];
        TMG_Category__c cat = new TMG_Category__c();
        cat.Name = 'Billing';
        cat.TMG_Project__c = proj.Id;
        cat.Due_Date__c = Date.today().addDays(14);
        cat.RecordTypeId = RecType.Id;
        insert cat;
        
        Milestone1_Milestone__c milestone = Milestone1_Test_Utility.sampleMilestone(proj.Id, parentMilestone.Id, 'SampleMilestone');
        milestone.TMG_Category__c = cat.id;
        insert milestone;
        
        Test.startTest();
        
        Set<Id> setIds = new Set<Id>();
        setIds.add(cat.id);
        
        Milestone1_Milestone_Trigger_Utility.populateCategoryTasksfields(setIds);
        
        Test.stopTest();
        
    }
    
    static testMethod void myUnitTest2() {
        
        Profile profileUsed;

        String ret = 'word' + math.rint(math.random() * 100000);
        for( Profile p : [ Select Id, PermissionsModifyAllData, Name from Profile where PermissionsModifyAllData = false limit 1 ] ){
           profileUsed = p;
        }
        String namePrefix = ret;

        User testUser = new User();
        testUser.Email = 'test2@test2.com';
        testUser.Username = ret + '@testuser2.com';
        testUser.LastName = 'test2';
        testUser.Alias = 'test2';
        testUser.ProfileId = profileUsed.Id;
        testUser.LanguageLocaleKey = 'en_US';
        testUser.LocaleSidKey = 'en_US';
        testUser.TimeZoneSidKey = 'America/Chicago';
        testUser.EmailEncodingKey = 'UTF-8';
        insert testUser;
        
        System.runAs(testUser) {
            
            RecordType RecType1 = [select Id from RecordType where SobjectType = 'Milestone1_Project__c' AND Name = 'CEO Succession'];
            Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProjectActive('SampleProject');
            proj.RecordTypeId = RecType1.Id;
            proj.Status__c = 'Submitted';
            insert proj;
            Milestone1_Milestone__c parentMilestone = Milestone1_Test_Utility.sampleMilestone(proj);
            
            TMGPProjectWizardCEOSuccessController con = new TMGPProjectWizardCEOSuccessController();
            con.milestoneId = proj.Id;
            Milestone1_Project__c proj1 = con.milestone;
            List<Milestone1_Milestone__c> participants = con.participants;
            string projectLink = con.projectLink;
            Milestone1_Milestone__c inteviewDeliverable = con.inteviewDeliverable;
            Milestone1_Milestone__c debriefDeliverable = con.debriefDeliverable;
            
            RecordType RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'Data Collection'];
            TMG_Category__c cat = new TMG_Category__c();
            cat.Name = 'Billing';
            cat.TMG_Project__c = proj.Id;
            cat.Due_Date__c = Date.today().addDays(14);
            cat.RecordTypeId = RecType.Id;
            insert cat;
            
            Milestone1_Milestone__c milestone = Milestone1_Test_Utility.sampleMilestone(proj.Id, parentMilestone.Id, 'SampleMilestone');
            milestone.TMG_Category__c = cat.id;
            //SSANDHU 00224743 START
            //insert milestone;
            //SSANDHU END   
        }
        
        Boolean perm = Milestone1_Milestone_Trigger_Utility.milestonePermissions('Account');
        system.assertEquals(perm,true);
        
        Test.startTest();
        
    }
    // added for the story #S-362576 #END
}