force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Interview Approved</fullName>
            </value>
            <value>
                <fullName>Referencing</fullName>
            </value>
            <value>
                <fullName>Writing</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/TMG_Category__c.field-meta.xml
<CustomField>
    <fullName>TMG_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>TMG_Category__c.TMG_Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TMG_Category__c</referenceTo>
    <relationshipLabel>TMG Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <inlineHelpText>The current status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>ADMIN ONLY</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved / Planning (95%)</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-billable</fullName>
                <isActive>false</isActive>
                <label>Non-billable</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <isActive>false</isActive>
                <label>Planning</label>
            </value>
            <value>
                <fullName>To Be Submitted</fullName>
                <isActive>false</isActive>
                <label>To Be Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/recordTypes/Advisory.recordType-meta.xml
<RecordType>
    <fullName>Advisory</fullName>
    <active>true</active>
    <label>Advisory</label>
</RecordType>

force-app/main/default/objects/TMG_Category__c/TMG_Category__c.object-meta.xml
<CustomObject>
    <label>TMG Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Category__c/fields/TMG_Project__c.field-meta.xml
<CustomField>
    <fullName>TMG_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMG Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipLabel>TMG Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/recordTypes/Coaching.recordType-meta.xml
<RecordType>
    <fullName>Coaching</fullName>
    <active>true</active>
    <description>Follow-on coaching as part of the original assessment contract</description>
    <label>Coaching</label>
</RecordType>

force-app/main/default/classes/TMGPProjectWizardCoachingAdvisoryConTest.cls
/**********************************************
/* Name : TMGPProjectWizardCoachingAdvisoryConTest
/* Created By : Shubham
/* Case : 00138614
/*********************************************/
@isTest
private class TMGPProjectWizardCoachingAdvisoryConTest {

    static testMethod void myUnitTest() {
        RecordType RecType1 = [select Id from RecordType where SobjectType = 'Milestone1_Project__c' AND Name = 'Advisory'];
        Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProjectActive('SampleProject');
        proj.RecordTypeId = RecType1.Id;
        proj.Status__c = 'Submitted'; //Added By Arihant for CASE#00222502
        insert proj;
        Milestone1_Milestone__c parentMilestone = Milestone1_Test_Utility.sampleMilestone(proj);
        Milestone1_Milestone__c milestone = Milestone1_Test_Utility.sampleMilestone(proj.Id, parentMilestone.Id, 'SampleMilestone');
        insert milestone;
        RecordType RecType = [select Id from RecordType where SobjectType = 'TMG_Category__c' AND Name = 'Coaching'];
        TMG_Category__c cat = new TMG_Category__c();
        cat.Name = 'Billing';
        cat.TMG_Project__c = proj.Id;
        cat.Due_Date__c = Date.today().addDays(14);
        cat.RecordTypeId = RecType.Id;
        insert cat;
        
        Test.startTest();
        TMGPProjectWizardCoachingAdvisoryCont con = new TMGPProjectWizardCoachingAdvisoryCont();
        con.milestoneId = proj.Id;
        Milestone1_Project__c proj1 = con.milestone;
        List<Milestone1_Milestone__c> deliverables = con.deliverables;
        TMG_Category__c cat1 = con.category;
        Test.stopTest();
    }
}