force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>This is the alias for a milestone.</description>
    <inlineHelpText>An alias helps you associate a task to a milestone using the single line entry home page component.</inlineHelpText>
    <label>Deliverable Alias</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Last_Coaching_Session__c.field-meta.xml
<CustomField>
    <fullName>Last_Coaching_Session__c</fullName>
    <label>Last Coaching Completed</label>
    <summarizedField>Milestone1_Task__c.Scheduled_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Milestone1_Task__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Coaching Session</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Milestone1_Task__c.Complete__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Milestone1_Task__c.Project_Milestone__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Main_Project_Debrief__c.field-meta.xml
<CustomField>
    <fullName>Main_Project_Debrief__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Key Stakeholder or Group debrief task for the project</description>
    <inlineHelpText>The Key Stakeholder or Group debrief task for the project</inlineHelpText>
    <label>Main Project Debrief</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone1_Task__c.Project_Milestone__r.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>Milestone1_Task__c.Complete__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Milestone1_Task__c</referenceTo>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Participant_contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TMG Deliverables (Participant Contact)</relationshipLabel>
    <relationshipName>TMG_Deliverables_1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/TMG_Primary__c.field-meta.xml
<CustomField>
    <fullName>TMG_Primary__c</fullName>
    <formula>Opportunity__r.TMG_Primary__r.FirstName &amp; &quot; &quot; &amp;  Opportunity__r.TMG_Primary__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TMG Primary</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>false</active>
    <description>DO NOT USE</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Milestone1_Milestone__c/recordTypes/Stakeholder_Debrief.recordType-meta.xml
<RecordType>
    <fullName>Stakeholder_Debrief</fullName>
    <active>true</active>
    <description>Use for all Stakeholder/Manager alignments &amp; debriefs</description>
    <label>Stakeholder Debrief</label>
</RecordType>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advisory Services</fullName>
            </value>
            <value>
                <fullName>Board Evaluation</fullName>
            </value>
            <value>
                <fullName>Coaching</fullName>
            </value>
            <value>
                <fullName>Executive Assessment</fullName>
            </value>
            <value>
                <fullName>Executive Assessment w/ Coaching</fullName>
            </value>
            <value>
                <fullName>Key Selection Criteria</fullName>
            </value>
            <value>
                <fullName>Leadership Accelerator</fullName>
            </value>
            <value>
                <fullName>Succession</fullName>
            </value>
            <value>
                <fullName>Team Effectiveness</fullName>
            </value>
            <value>
                <fullName>Renewal Coaching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <formula>Opportunity__r.Participant_Contact__r.FirstName &amp;&quot; &quot;&amp; Opportunity__r.Participant_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Participant Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/TMG_Primary__c.field-meta.xml
<CustomField>
    <fullName>TMG_Primary__c</fullName>
    <formula>Opportunity__r.TMG_Primary__r.pse__Salesforce_User__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TMG Primary</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/recordTypes/Advisory.recordType-meta.xml
<RecordType>
    <fullName>Advisory</fullName>
    <active>true</active>
    <label>Advisory</label>
</RecordType>

force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>TMG Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Project_Milestone__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task.</inlineHelpText>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
    <label>Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/First_Chair_User__c.field-meta.xml
<CustomField>
    <fullName>First_Chair_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Chair</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Last_Coaching_Session__c.field-meta.xml
<CustomField>
    <fullName>Last_Coaching_Session__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify the last touch point in a coaching engagement. When scehduled this will trigger an alert to the operations specialist and project leads to initiate renewal discussions</description>
    <inlineHelpText>Identifies the last contractual touch point for an engagement</inlineHelpText>
    <label>Last Coaching Session</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Project_Milestone__c</fullName>
    <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
    <label>Deliverable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone1_Milestone__c.Complete__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Milestone1_Milestone__c</referenceTo>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Created for Story S-349354</description>
    <formula>Project_Milestone__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Second_Chair_User__c.field-meta.xml
<CustomField>
    <fullName>Second_Chair_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Second Chair</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Task_Stage__c.field-meta.xml
<CustomField>
    <fullName>Task_Stage__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <inlineHelpText>Where is this task on the road to completion?</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assigned</fullName>
            </value>
            <value>
                <fullName>To Be Scheduled</fullName>
            </value>
            <value>
                <fullName>Client Contacted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled by TMG</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>TBR (To Be Rescheduled)</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>To Be Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Confirmed</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Incomplete (Calendar Conflicts)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/recordTypes/Stakeholder_Debrief.recordType-meta.xml
<RecordType>
    <fullName>Stakeholder_Debrief</fullName>
    <active>true</active>
    <label>Stakeholder Debrief</label>
</RecordType>

force-app/main/default/classes/Milestone1_Task_Trigger_Utility_Test.cls
// 
// (c) 2015 Appirio, Inc.
//
// 
//
// 10 AUG 2015     Nick Sharp      Modified   S-340006
// 
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, 
this list of conditions and the following disclaimer in the documentation 
and/or other materials provided with the distribution.
* Neither the name of the salesforce.com, Inc. nor the names of its contributors 
may be used to endorse or promote products derived from this software 
without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
/**
* This Class test Task Trigger functionality  
*/
//START -- Updated by komal | C-00277296 | 17/04/2020 | ['SeeAllData=true to false' inorder to fix the error "No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. Create CMC Issue"]
@isTest(SeeAllData=false)
//END -- Updated by Komal | C-00277296 | 17/04/2020 |
private class Milestone1_Task_Trigger_Utility_Test {
    
    /**
* Test exceeded chatter suscription
*/
    static testMethod void chatterSubscriptionLimitExceeded() {
        // Create a poject
        Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProject('Chatter Blow');
        insert proj;
        
        // Create a milestone
        Milestone1_Milestone__c mstone = Milestone1_Test_Utility.sampleMilestone(proj);
        insert mstone;
        
        // Add 600 tasks to the milestone to exceed chatter user subscription limit
        Test.startTest();
        List<Milestone1_Task__c> lTask = new List<Milestone1_Task__c>();
        
        Milestone1_Task_Trigger_Utility.checkOWDPermissions(lTask); //added for the case #S-362576
        
        for(Integer j = 0; j < 6; j++){          
            for(Integer i = 0; i < 100; i++){
                lTask.add( Milestone1_Test_Utility.sampleTask(mstone.Id) );
            }
            
            try{
                insert lTask;
            }
            catch(Exception e){
                if( e.getMessage().contains( Milestone1_Task_Trigger_Utility.SUBSCRIPTION_LIMIT_EXCEEDED )){
                    system.assert(true);
                }
                else{
                    //system.assert(false, e.getMessage());
                }
            }
            
            lTask.clear();
        }
        //START NSHARP S-340006 8.10.15
        Milestone1_Task_Trigger_Utility.checkOWDPermissions(lTask);
        //END NSHARP S-340006 8.10.15
        Test.stopTest();
    }
    /* Start - Jai Gupta - S-559561 - Aug 30,2018 */
    static testmethod void populateOpportunityOnLastCoachingTest() {
        
        Milestone1_Task__c mt = getMileStoneTask();
        List<Milestone1_Milestone__c> idLst = [Select id from Milestone1_Milestone__c  WHERE Complete__c = false and Total_Open_Tasks__c = 2 and
                                               Main_Project_Debrief__r.Project_Milestone__r.RecordType.DeveloperName = null 
                                               AND RecordType.DeveloperName = 'Stakeholder_Debrief' ];
        mt.Name = 'taskName';
        mt.RecordType = [SELECT id FROM RecordType WHERE Name = 'Coaching Session' ];
        UserRole r = [SELECT Id FROM UserRole WHERE Name='Miles Group' limit 1];
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' limit 1];
        User u = createTestUser(p.Id,r.Id,'test','user1');
        User runUser=[Select id from User where Name='Stephen Miles'];
        System.runAs(runUser){
            mt.Assigned_To__c = runUser.id ;
            mt.Complete__c = True;
            //mt.Project_Milestone__c = idLst.get(0).id;
            mt.Task_Stage__c  = 'Scheduled';
            mt.Scheduled_Date__c  = System.today().addDays(-7);
            mt.First_Chair_User__c = runUser.id;
            mt.Second_Chair_User__c = runUser.id;
        }
        //Milestone1_Task__c objNew=[Select id from Milestone1_Task__c limit 1];
        Test.startTest();
        update mt ;
        //START --Updated by Komal | C-00277296 | 17/04/2020 | [in order to fix error "No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. Create CMC Issue"]      
        Test.stopTest();
        //END -- Updated by Komal | C-00277296 | 17/04/2020 |     
        Milestone1_Task__c newmt = [Select Id,Last_Coaching_Session__c, Opportunity_Name__c From Milestone1_Task__c where Id = :mt.Id] ;
        //system.assertEquals(false,newmt.Last_Coaching_Session__c);
        //system.assertEquals(null,newmt.Opportunity_Name__c);
        
        mt.Last_Coaching_Session__c = true ;
        update mt ;
        
        //newmt = [Select Id,Last_Coaching_Session__c, Opportunity_Name__c From Milestone1_Task__c where Id = :mt.Id] ;
        //system.assertEquals(true,newmt.Last_Coaching_Session__c);
        //system.assertNotEquals(null,newmt.Opportunity_Name__c);
        
        //START --Commented by Komal | C-00277296 | 17/04/2020 | [in order to fix error "No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. Create CMC Issue"] 
        //Test.stopTest();
        //END -- Commented by Komal | C-00277296 | 17/04/2020 | 
    } 
    private static Milestone1_Task__c getMileStoneTask() {
        Account a = new Account();
        a.Name = 'New Test Account';
        insert a;
        
        Contact con = new Contact();
        con.FirstName = 'Test';   // Commented by Shalini Sati for case 00243902 on date 12/12/2018
        con.LastName = 'Contact';
        con.AccountId = a.Id;
        con.Account_Name__c = a.Id;
        insert con;
        //START --Added by Komal | C-00277296 | 17/04/2020 | [in order to fix error "No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. Create CMC Issue"  
        FFA_TestUtility testUtil = new FFA_TestUtility();
        User testUser2 = testUtil.newUserSysAdmin(true);
        Contact testContact2 = testUtil.newResource(true, a.Id, testUser2.Id);  
        //END -- Added by Komal | C-00277296 | 17/04/2020 |  
        Opportunity opp = New Opportunity();
        opp.accountId = a.id;
        opp.name = 'Test oppty';
        opp.Membership_Begins__c = date.today();
        opp.Membership_Expires__c = opp.Membership_Begins__c + 365;
        opp.Invoice_Date__c = date.today();
        opp.Payment_Date__c = date.today();
        opp.amount = 100.00;
        opp.StageName = '100 - Signed Contract';
        opp.Group2__c = 'The Miles Group';
        opp.Engagement_Type__c = 'Advisory';
        opp.Lead_Contact_Source__c = con.id;
        opp.Participant_Contact__c = con.id;
        opp.Parent_Account_Contact__c = con.id;
        opp.isRenewalOpportunity__c = true ;
        opp.recordTypeID = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Advisory Services').getRecordTypeId();
        opp.Project_Name__c = 'Test';
        opp.CloseDate = date.today() + 365;
        opp.Project_Start_Date__c = date.today();
        opp.Project_End_Date__c =opp.Project_Start_Date__c.addmonths(9);
        //START --added by Komal | C-00277296 | 17/04/2020 | [in order to fix error "No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. Create CMC Issue"]  
        opp.TMG_Primary__c=testContact2.id; 
        insert opp;
        //END -- added by Komal | C-00277296 | 17/04/2020 | 
        String taskName = 'Unit Test Email Notes 123';
        Milestone1_Project__c proj = Milestone1_Test_Utility.sampleProject('proj');
        insert proj;
        Milestone1_Milestone__c ms1 = Milestone1_Test_Utility.sampleMilestone(proj.Id, null, 'ms1');
        ms1.Alias__c = 'unit_test';
        insert ms1;
        List<Milestone1_Milestone__c> idLst = [Select id from Milestone1_Milestone__c  WHERE Complete__c = false and Total_Open_Tasks__c = 2 and
                                               Main_Project_Debrief__r.Project_Milestone__r.RecordType.DeveloperName = null 
                                               AND RecordType.DeveloperName = 'Stakeholder_Debrief'];
        
        Milestone1_Task__c msTask1 = Milestone1_Test_Utility.sampleTask(ms1.Id);
        msTask1.Name = taskName;
        msTask1.RecordType = [SELECT id FROM RecordType WHERE Name = 'Coaching Session'];
        UserRole r = [SELECT Id FROM UserRole WHERE Name='Miles Group' limit 1];
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' limit 1];
        User u = createTestUser(p.Id,r.Id,'test','user1');
        User runUser=[Select id from User where Name='Stephen Miles'];
        System.runAs(runUser){
            msTask1.Assigned_To__c = runUser.id ;
            msTask1.Complete__c = True;
            //START --Commented by Komal | C-00277296 | 17/04/2020 | [in order to fix error "No more than one executeBatch can be called from within a test method. Please make sure the iterable returned from your start method matches the batch size, resulting in one executeBatch invocation. Create CMC Issue"]
            //msTask1.Project_Milestone__c = idLst.get(0).id;
            ////END -- Commented by Komal | C-00277296 | 17/04/2020 | 
            msTask1.Task_Stage__c  = 'Scheduled';
            msTask1.Scheduled_Date__c  = System.today().addDays(-7);
            msTask1.First_Chair_User__c = runUser.id;
            msTask1.Second_Chair_User__c = runUser.id;
            insert msTask1;
        }
        return msTask1;
        //  test.startTest(); 
    }
    // create User
    public static User createTestUser(Id profID, Id roleId, String fName, String lName) {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              ProfileId = profId,
                              UserRoleId = roleId
                             );
        // START JWEBB C-00228360 05/14/2018
        // insert tuser;
        // END JWEBB C-00228360 05/14/2018
        return tuser;
    }
    
    /* End - Jai Gupta - S-559561 */
}