force-app/main/default/objects/Milestone1_Milestone__c/Milestone1_Milestone__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <label>TMG Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Assessed_Executive__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TMG Deliverables (Assessments &amp; Coaching)</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/First_Chair__c.field-meta.xml
<CustomField>
    <fullName>First_Chair__c</fullName>
    <label>First Chair</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Matt Bedwell</fullName>
            </value>
            <value>
                <fullName>Taylor Griffin</fullName>
            </value>
            <value>
                <fullName>Courtney Hamilton</fullName>
            </value>
            <value>
                <fullName>Jeff Jones</fullName>
            </value>
            <value>
                <fullName>Elizabeth Kelly</fullName>
            </value>
            <value>
                <fullName>Stephanie Loquvam</fullName>
            </value>
            <value>
                <fullName>Stephen Miles</fullName>
            </value>
            <value>
                <fullName>John Nasr</fullName>
            </value>
            <value>
                <fullName>Billy Stern</fullName>
            </value>
            <value>
                <fullName>Allison Widman</fullName>
            </value>
            <value>
                <fullName>Adam Wilkes</fullName>
            </value>
            <value>
                <fullName>External Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Kickoff__c.field-meta.xml
<CustomField>
    <fullName>Kickoff__c</fullName>
    <inlineHelpText>Contract start date</inlineHelpText>
    <label>Kickoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Project_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Project_Wizard__c</fullName>
    <description>Automatically sets the Project Wizard for a deliverable based on the project. Used for creating PW as a related user for Deliverable work flows.</description>
    <formula>Project__r.Project_Wizard__r.Id</formula>
    <label>Project Wizard</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Be Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Interview Approved</fullName>
            </value>
            <value>
                <fullName>Referencing</fullName>
            </value>
            <value>
                <fullName>Writing</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Milestone__c/fields/TMG_Category__c.field-meta.xml
<CustomField>
    <fullName>TMG_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>TMG_Category__c.TMG_Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TMG_Category__c</referenceTo>
    <relationshipLabel>TMG Deliverables</relationshipLabel>
    <relationshipName>Deliverables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/Milestone1_Project__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>TMG Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Board_Dates__c.field-meta.xml
<CustomField>
    <fullName>Board_Dates__c</fullName>
    <description>List of Board meetings for the term of the engagement</description>
    <label>Board Dates</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Deadline__c.field-meta.xml
<CustomField>
    <fullName>Deadline__c</fullName>
    <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
    <label>Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Kickoff__c.field-meta.xml
<CustomField>
    <fullName>Kickoff__c</fullName>
    <inlineHelpText>What date should this project start?</inlineHelpText>
    <label>Kickoff</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Project_Wizard__c.field-meta.xml
<CustomField>
    <fullName>Project_Wizard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Wizard</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <inlineHelpText>The current status of the project.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed/Won</fullName>
            </value>
            <value>
                <fullName>Closed/Lost</fullName>
            </value>
            <value>
                <fullName>ADMIN ONLY</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved / Planning (95%)</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Non-billable</fullName>
                <isActive>false</isActive>
                <label>Non-billable</label>
            </value>
            <value>
                <fullName>Planning</fullName>
                <isActive>false</isActive>
                <label>Planning</label>
            </value>
            <value>
                <fullName>To Be Submitted</fullName>
                <isActive>false</isActive>
                <label>To Be Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/Team_Offsite__c.field-meta.xml
<CustomField>
    <fullName>Team_Offsite__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked if there is a team offsite deliverable in contract (or stated otherwise by the PW)</description>
    <inlineHelpText>Please check if there is a team offsite deliverable in the contract</inlineHelpText>
    <label>Team Offsite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/fields/X360__c.field-meta.xml
<CustomField>
    <fullName>X360__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked if there is a 360 assessment in the contract (or stated otherwise by the PW)</description>
    <inlineHelpText>Check if a 360 assessment is required per contract or otherwise</inlineHelpText>
    <label>360</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Milestone1_Project__c/recordTypes/Advisory.recordType-meta.xml
<RecordType>
    <fullName>Advisory</fullName>
    <active>true</active>
    <label>Advisory</label>
</RecordType>

force-app/main/default/objects/TMG_Category__c/TMG_Category__c.object-meta.xml
<CustomObject>
    <label>TMG Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Category__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Opportunity_Name__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency of coaching sessions</description>
    <inlineHelpText>Frequency of coaching sessions</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Every 6 weeks</fullName>
            </value>
            <value>
                <fullName>See Description</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Number_of_in_person_meetings__c.field-meta.xml
<CustomField>
    <fullName>Number_of_in_person_meetings__c</fullName>
    <description>Number of in-person meeting as outlined in the contract</description>
    <inlineHelpText>Number of in-person meeting as outlined in the contract</inlineHelpText>
    <label>Number of in-person meetings</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>When practical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Team_Offsite__c.field-meta.xml
<CustomField>
    <fullName>Team_Offsite__c</fullName>
    <description>Date of the scheduled offsite event</description>
    <inlineHelpText>Date of the scheduled offsite event</inlineHelpText>
    <label>Team Offsite</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/TMG_Project__c.field-meta.xml
<CustomField>
    <fullName>TMG_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TMG Project</label>
    <referenceTo>Milestone1_Project__c</referenceTo>
    <relationshipLabel>TMG Categories</relationshipLabel>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Coaching session type (e.g. in-person)</description>
    <inlineHelpText>Coaching session type (e.g. in-person)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Combination (in-person, phone, video)</fullName>
                <default>true</default>
                <label>Combination (in-person, phone, video)</label>
            </value>
            <value>
                <fullName>In-person</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Unspecified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TMG_Category__c/recordTypes/Coaching.recordType-meta.xml
<RecordType>
    <fullName>Coaching</fullName>
    <active>true</active>
    <description>Follow-on coaching as part of the original assessment contract</description>
    <label>Coaching</label>
</RecordType>

force-app/main/default/classes/TMGPProjectWizardCoachingAdvisoryCont.cls
global class TMGPProjectWizardCoachingAdvisoryCont {
    global string milestoneId{get; set;}
    global Milestone1_Project__c milestone{
        get{
            Milestone1_Project__c milestone = new Milestone1_Project__c();
            if(milestoneId != null){
                List<Milestone1_Project__c> milestones = new List<Milestone1_Project__c>([Select Id, Name, RecordType.Name, Project_Wizard__r.Name, Status__c, Account__r.Name, Kickoff__c, Client__r.Name, Deadline__c, Opportunity__r.Name,  Description__c,  Board_Dates__c, X360__c, Team_Offsite__c from Milestone1_Project__c where Id=:milestoneId AND (RecordType.Name = 'Executive Coaching' OR RecordType.Name = 'Advisory') Limit 1]);
                if(milestones.size()>0){
                    milestone = milestones.get(0);
                }
            }
            return milestone;
        }
        set;
    }
    global TMG_Category__c category{
        get{
            TMG_Category__c category = new TMG_Category__c();
            if(milestoneId != null){
                List<TMG_Category__c> categories = new List<TMG_Category__c>([Select id, Frequency__c, Type__c, Number_of_in_person_meetings__c, Description__c from TMG_Category__c where TMG_Project__c =: milestoneId and recordType.Name = 'Coaching' and Due_Date__c != null order by Due_Date__c asc limit 1]);
                if(categories.size() > 0){
                    category.Frequency__c = categories.get(0).Frequency__c;
                    category.Type__c = categories.get(0).Type__c;
                    category.Number_of_in_person_meetings__c = categories.get(0).Number_of_in_person_meetings__c;
                    category.Description__c = categories.get(0).Description__c;
                }
            }
            return category;
        }
        set;
    }
    global Milestone1_Milestone__c[] deliverables{
        get{
            List<Milestone1_Milestone__c> deliverables;
            Milestone1_Milestone__c deliverable = new Milestone1_Milestone__c();
            if(milestoneId != null){
                deliverables = new List<Milestone1_Milestone__c>([Select Id, Assessed_Executive__r.Name, First_Chair__c from Milestone1_Milestone__c where Project__c = :milestoneId AND RecordType.Name = 'Executive Coaching' order by Assessed_Executive__r.Name asc]);
            }
            return deliverables;
        }
        set;
    }
}