force-app/main/default/objects/Deal_Sheet_Line_Item__c/Deal_Sheet_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Deal Sheet Line Item</label>
    <nameField>
        <displayFormat>DSLI-{000000}</displayFormat>
        <label>Deal Sheet Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Sheet Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Calendar_Day__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Day__c</fullName>
    <description>This field is created as a replica of calendar Workdays</description>
    <label>Calendar Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Fixed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Revenue__c</fullName>
    <label>Fixed Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Vice President</fullName>
            </value>
            <value>
                <fullName>Senior Director</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Associate Director</fullName>
            </value>
            <value>
                <fullName>Associate Consultant</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateDealSheetCalendarDaysBatch.cls
/*********************************************************************************
Name : Harendra Sain
Created By : Appirio  
Created Date : 13 Jan 2015
Purpose : Batch class to update the calendar days
*********************************************************************************/
global class UpdateDealSheetCalendarDaysBatch  implements Database.Batchable<sObject>{
  
   global String Query;
   
    // Constructor
    global UpdateDealSheetCalendarDaysBatch(){        
        
    }
    
      // Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
     
     Query = 'SELECT id, Calendar_Day__c, Fixed_Revenue__c, Role__c, Fixed_Cost__c, Start_Date__c, End_Date__c from Deal_Sheet_Line_Item__c where Start_Date__c != null AND End_Date__c != null ';
              
        return Database.getQueryLocator(Query);
      
    }
    
    //Execute Method
    global void execute(Database.BatchableContext BC,List<Deal_Sheet_Line_Item__c> DealSheetLineItem){ 
    
      List<Deal_Sheet_Line_Item__c> DsliToUpdate = new List<Deal_Sheet_Line_Item__c>();    
      
        for(Deal_Sheet_Line_Item__c dsli: DealSheetLineItem){           
           dsli.Calendar_Day__c = HoursBetweenTwoDates(dsli.Start_Date__c, dsli.End_Date__c);
           DsliToUpdate.add(dsli);        
        }
        if(DsliToUpdate.size() > 0){
           update DsliToUpdate;
        }
      }
      global Integer HoursBetweenTwoDates( Date startDate ,Date endDate){
        DateTime dtStart = DateTime.newInstance(startDate.year(),startDate.month(),startDate.day(),0,0,0);
        DateTime dtEnd = DateTime.newInstance(endDate.year(),endDate.month(),endDate.day(),0,0,0);
        Integer dayCount = 0;
        if(dtStart == null || dtEnd == null) return 0;
    
          if(dtStart > dtEnd) {
            DateTime dtTemp = dtEnd;
            dtEnd = dtStart;
            dtStart = dtTemp;
          }
          while (dtStart.Date() <= dtEnd.Date()) {
                   if (dtStart.format('EEE') != 'Sat' && dtStart.format('EEE') != 'Sun'){
                    dayCount ++;
            }
              dtStart = datetime.newInstance(dtStart.Year(), dtStart.Month(), dtStart.Day()+1, 00, 00, 00);
          }
          return dayCount;
      }
     // Finish Method
    global void finish(Database.BatchableContext BC){
        
    }
      
}