force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Connector object that associates a Student to a Class.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Enrollment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use to identify type of class</inlineHelpText>
    <label>Class</label>
    <referenceTo>SFDC_Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>R00N40000001QAyfEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Student Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N40000001QAygEAG</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <formula>TEXT(Class__r.Facility__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Used to identify the facility where student was trained</inlineHelpText>
    <label>Facility</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Use to identfy participate status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/SFDC_Class__c.object-meta.xml
<CustomObject>
    <description>Track the date and location of where your various Courses will be taught, and who has enrolled in this Class.</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_Class__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the class to the course</description>
    <label>Course</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>R00N40000001QAyiEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/fields/Staff_Contact__c.field-meta.xml
<CustomField>
    <fullName>Staff_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Instructor</inlineHelpText>
    <label>Staff Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>R00N40000001QAyhEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClassEnrollmentsInLineControllerTest.cls
/***************************************
Author        : Appirio India [Hitesh Pareek]
Date          : Feb 20, 2017
Purpose       : S-467680
***************************************/
@isTest
private class ClassEnrollmentsInLineControllerTest {

    static testMethod void testEnrollmentInLineList() {
        Account acc = new Account(name='test Acc');
        insert acc;
        
        Contact con = new Contact(AccountId = acc.id, LastName = 'Test Con');
        insert con;
        
        Product2 prod = new Product2();
        prod.Name = 'testProd';
        insert prod;
        
        SFDC_Class__c cls = new SFDC_Class__c();
        cls.Product2__c = prod.id;
        //cls.Staff_Contact__c = con.id;
        cls.Facility__c = 'London';
        cls.Max_Capacity__c = 30;
        insert cls;        
                
        Class_Enrollment__c enroll = new Class_Enrollment__c();
        enroll.Contact__c = con.id;
        enroll.Class__c = cls.id;
        insert enroll;
        
        Test.startTest();
        PageReference p = Page.ClassEnrollmentsInLine;
        Test.setCurrentPage(p);
        ApexPages.StandardController sc = new ApexPages.StandardController(cls);
        ClassEnrollmentsInLineController ext = new ClassEnrollmentsInLineController(sc);
        system.assert(ext.enrollments.size() >0);
        for(Class_Enrollment__c en :ext.enrollments){
            en.Status__c = 'Prospect';
        }
        ext.SaveEnrollments();
        ext.enrollmentToBedeleted = ext.enrollments.get(0).id;
        ext.deleteEnrollmentRecord();        
        Test.stopTest();
    }
}