force-app/main/default/objects/Class_Enrollment__c/Class_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Connector object that associates a Student to a Class.</description>
    <label>Class Enrollment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Enrollment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Enrollment__c/fields/Certificate_Issued__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Issued__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use to indicate if a certificate has been issued</inlineHelpText>
    <label>Certificate Issued</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use to identify type of class</inlineHelpText>
    <label>Class</label>
    <referenceTo>SFDC_Class__c</referenceTo>
    <relationshipLabel>Class Enrollments</relationshipLabel>
    <relationshipName>R00N40000001QAyfEAG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Class_Type__c.field-meta.xml
<CustomField>
    <fullName>Class_Type__c</fullName>
    <label>Class Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yellow Belt</fullName>
            </value>
            <value>
                <fullName>Green Belt</fullName>
            </value>
            <value>
                <fullName>Black Belt</fullName>
            </value>
            <value>
                <fullName>Master Black Belt</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Student Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00N40000001QAygEAG</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Other__c.field-meta.xml
<CustomField>
    <fullName>Other__c</fullName>
    <label>Other</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Plaque_Issued__c.field-meta.xml
<CustomField>
    <fullName>Plaque_Issued__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Use to identify if a plaque has been issued</inlineHelpText>
    <label>Plaque Issued</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Use to identfy participate status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Enrollment__c/fields/Test_Result__c.field-meta.xml
<CustomField>
    <fullName>Test_Result__c</fullName>
    <inlineHelpText>Enter the score or test results here</inlineHelpText>
    <label>Test Result</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_Class__c/SFDC_Class__c.object-meta.xml
<CustomObject>
    <description>Track the date and location of where your various Courses will be taught, and who has enrolled in this Class.</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClassEnrollmentsInLineController.cls
/***************************************
Author        : Appirio India [Hitesh Pareek]
Date          : Feb 20, 2017
Purpose       : S-467680
***************************************/
public with sharing class ClassEnrollmentsInLineController {
    public List<Class_Enrollment__c> enrollments {get; set;}
    public string newEnrollURL {get;set;}
    public string enrollmentToBedeleted {get;set;}
    public SFDC_Class__c classRecord {get;set;}
    public ClassEnrollmentsInLineController(ApexPages.StandardController sc){
        if(!Test.isRunningTest())
            sc.addFields(new List<String>{'name'});
        classRecord = (SFDC_Class__c )sc.getRecord();
        if(classRecord != null){
        enrollments = new List<Class_Enrollment__c>();
        for(Class_Enrollment__c enrollment :[select Name,Class__c,Contact__r.Name,Certificate_Issued__c,Certified__c,Status__c,Plaque_Issued__c,Test_Result__c,Other__c,Class_Type__c 
                                                    from Class_Enrollment__c 
                                                        where Class__c =:classRecord.id]){
                enrollments.add(enrollment );
           }            
            newEnrollURL = URL.getSalesforceBaseUrl().toExternalForm()+'/a4w/e?CF00NF0000008uppY='+classRecord.name+'&CF00NF0000008uppY_lkid='+classRecord.id+'&retURL=/'+classRecord.id+'&save_new_url=/'+classRecord.id;
        }
    }
        
    
    public PageReference SaveEnrollments(){
        if(enrollments != null && !enrollments.isempty()){
            update enrollments;
        }
        return null;
    }       
    
    public void deleteEnrollmentRecord(){        
        if(enrollmentToBedeleted != null){
            delete new List<Class_Enrollment__c>{new Class_Enrollment__c(id=enrollmentToBedeleted)};            
        }                
    }        
}