force-app/main/default/objects/Project_Benefit__c/Project_Benefit__c.object-meta.xml
<CustomObject>
    <label>Project Benefit</label>
    <nameField>
        <label>Project Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Benefit__c/fields/Client_logo__c.field-meta.xml
<CustomField>
    <fullName>Client_logo__c</fullName>
    <label>Client logo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project_Benefit__c/fields/Project_Closeout__c.field-meta.xml
<CustomField>
    <fullName>Project_Closeout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Closeout</label>
    <referenceTo>Project_Closeout__c</referenceTo>
    <relationshipLabel>Project Benefits</relationshipLabel>
    <relationshipName>Project_Benefits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Closeout__c/Project_Closeout__c.object-meta.xml
<CustomObject>
    <label>Project Closeout</label>
    <nameField>
        <label>Project Closeout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Closeout__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Project Closeouts</relationshipLabel>
    <relationshipName>Project_Closeouts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/projectBenefitTriggerHandler.cls
public with sharing class projectBenefitTriggerHandler {
    
    public projectBenefitTriggerHandler (){
        
    }
    
   public void OnBeforeInsert(Project_Benefit__c [] newlist){
       
       updateLogo(newList);
    }
    
    public void OnBeforeUpdate(Project_Benefit__c[] oldList, Project_Benefit__c[] newList, Map<ID, Project_Benefit__c> newMap){
        updateLogo(newList);
        
        
    }
    
    public void updateLogo(Project_Benefit__c [] newlist){
    
    list<Project_Benefit__c> pbList = new list<Project_Benefit__c>();
    Map<Id,String> projBenMap = new Map<id,String>();    
    for(Project_Benefit__c pb: newlist){
        projBenMap.put(pb.Project_Closeout__c,'');
    }
        
    for(Project_Closeout__c pc: [Select id,Project__r.pse__Account__r.Logo__c from Project_Closeout__c where Id in :projBenMap.keyset()]){
        projBenMap.put(pc.id,pc.Project__r.pse__Account__r.Logo__c);
    }
        
    for(Project_Benefit__c pb: newlist){
        
        if( pb.Client_logo__c == null || pb.Client_logo__c == '' ){
            
            pb.Client_logo__c = projBenMap.get(pb.Project_Closeout__c);
        }
    }
    }    
    
}