force-app/main/default/objects/Mid_Year_Review__c/Mid_Year_Review__c.object-meta.xml
<CustomObject>
    <description>Mid-Year Reviews</description>
    <label>Mid-Year Review</label>
    <nameField>
        <displayFormat>MYR{000000}</displayFormat>
        <label>Mid-Year Review No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mid-Year Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mid_Year_Review__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <label>Manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ashcroft, Paul</fullName>
            </value>
            <value>
                <fullName>Burke, Ashley</fullName>
            </value>
            <value>
                <fullName>Dix, Wayne</fullName>
            </value>
            <value>
                <fullName>Evans, Sharlene</fullName>
            </value>
            <value>
                <fullName>Kramer, Nick</fullName>
            </value>
            <value>
                <fullName>Miller, David</fullName>
            </value>
            <value>
                <fullName>Rodgers, John</fullName>
            </value>
            <value>
                <fullName>Sachdeva, Sachin</fullName>
            </value>
            <value>
                <fullName>Silvers, Bob</fullName>
            </value>
            <value>
                <fullName>Thangavelsamy, Raj</fullName>
            </value>
            <value>
                <fullName>Asbeck, Fred</fullName>
            </value>
            <value>
                <fullName>Houser, Dan</fullName>
            </value>
            <value>
                <fullName>Niles, Dave</fullName>
            </value>
            <value>
                <fullName>Meil, Jason</fullName>
            </value>
            <value>
                <fullName>Silvers, Jennifer</fullName>
            </value>
            <value>
                <fullName>Schiele, Kim</fullName>
            </value>
            <value>
                <fullName>Makhmali, Nika</fullName>
            </value>
            <value>
                <fullName>Miller, Scott</fullName>
            </value>
            <value>
                <fullName>Madden, Tricia</fullName>
            </value>
            <value>
                <fullName>Krajacic, Jeff</fullName>
            </value>
            <value>
                <fullName>Katz, Matt</fullName>
            </value>
            <value>
                <fullName>Brown, Reuben</fullName>
            </value>
            <value>
                <fullName>Muhota, Kim</fullName>
            </value>
            <value>
                <fullName>Bloomfield, Jon</fullName>
                <isActive>false</isActive>
                <label>Bloomfield, Jon</label>
            </value>
            <value>
                <fullName>Costa, Rafael</fullName>
                <isActive>false</isActive>
                <label>Costa, Rafael</label>
            </value>
            <value>
                <fullName>Covelli, John</fullName>
                <isActive>false</isActive>
                <label>Covelli, John</label>
            </value>
            <value>
                <fullName>Homann, Stefan</fullName>
                <isActive>false</isActive>
                <label>Homann, Stefan</label>
            </value>
            <value>
                <fullName>Kaiser, Thomas</fullName>
                <isActive>false</isActive>
                <label>Kaiser, Thomas</label>
            </value>
            <value>
                <fullName>Kaufmann, Julian</fullName>
                <isActive>false</isActive>
                <label>Kaufmann, Julian</label>
            </value>
            <value>
                <fullName>Lawrence, Chuck</fullName>
                <isActive>false</isActive>
                <label>Lawrence, Chuck</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Year_end_Review__c/Year_end_Review__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Year-End Review</label>
    <nameField>
        <displayFormat>YER{000000}</displayFormat>
        <label>Year End Review No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Year_end_Review__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <label>Manager</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asbeck, Fred</fullName>
            </value>
            <value>
                <fullName>Ashcroft, Paul</fullName>
            </value>
            <value>
                <fullName>Brown, Reuben</fullName>
            </value>
            <value>
                <fullName>Burke, Ashley</fullName>
            </value>
            <value>
                <fullName>de Janosi, Paul</fullName>
            </value>
            <value>
                <fullName>Dix, Wayne</fullName>
            </value>
            <value>
                <fullName>Houser, Dan</fullName>
            </value>
            <value>
                <fullName>Kaiser, Thomas</fullName>
            </value>
            <value>
                <fullName>Katz, Matt</fullName>
            </value>
            <value>
                <fullName>Krajacic, Jeff</fullName>
            </value>
            <value>
                <fullName>Kramer, Nick</fullName>
            </value>
            <value>
                <fullName>Lambert, Eddie</fullName>
            </value>
            <value>
                <fullName>Lawrence, Chuck</fullName>
            </value>
            <value>
                <fullName>Madden, Tricia</fullName>
            </value>
            <value>
                <fullName>Makhmali, Nika</fullName>
            </value>
            <value>
                <fullName>Meil, Jason</fullName>
            </value>
            <value>
                <fullName>Miller, David</fullName>
            </value>
            <value>
                <fullName>Miller, Scott</fullName>
            </value>
            <value>
                <fullName>Muhota, Kim</fullName>
            </value>
            <value>
                <fullName>Niles, Dave</fullName>
            </value>
            <value>
                <fullName>Nordyke, Brian</fullName>
            </value>
            <value>
                <fullName>Randeria, Sonal</fullName>
            </value>
            <value>
                <fullName>Rodgers, John</fullName>
            </value>
            <value>
                <fullName>Schiele, Kim</fullName>
            </value>
            <value>
                <fullName>Silvers, Bob</fullName>
            </value>
            <value>
                <fullName>Silvers, Jennifer</fullName>
            </value>
            <value>
                <fullName>Ventry, Chris</fullName>
            </value>
            <value>
                <fullName>Bloomfield, Jon</fullName>
                <isActive>false</isActive>
                <label>Bloomfield, Jon</label>
            </value>
            <value>
                <fullName>Costa, Rafael</fullName>
                <isActive>false</isActive>
                <label>Costa, Rafael</label>
            </value>
            <value>
                <fullName>Covelli, John</fullName>
                <isActive>false</isActive>
                <label>Covelli, John</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Year_end_Review__c/fields/Mid_Year_Review__c.field-meta.xml
<CustomField>
    <fullName>Mid_Year_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mid-Year Review</label>
    <referenceTo>Mid_Year_Review__c</referenceTo>
    <relationshipName>Year_end_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/YearEndReviewTriggerHandlerTest.cls
@isTest
private class YearEndReviewTriggerHandlerTest {
    static testmethod void testTriggerHandler() {
        Mid_Year_Review__c myr = new Mid_Year_Review__c();
        insert myr;
        //START -- Added by Shivani for S-637724 on 03/09/2019
        Mid_Year_Review__c myr1 = new Mid_Year_Review__c();
        insert myr1;
        //END -- Added by Shivani for S-637724 on 03/09/2019
        Year_end_Review__c yer = new Year_end_Review__c(Mid_Year_Review__c=myr.Id);
        insert yer;
        yer.Manager__c = 'Ashcroft, Paul';
        update yer;
        //START -- Added by Shivani for S-637724 on 03/09/2019
        yer.Mid_Year_Review__c = myr1.Id;
        update yer;

        YearEndReviewTriggerHandler y = new YearEndReviewTriggerHandler();
        y.YearEndReviewTriggerHandler();
        //END -- Added by Shivani for S-637724 on 03/09/2019
    }
}