force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/DisplayfilterLogic__c.field-meta.xml
<CustomField>
    <fullName>DisplayfilterLogic__c</fullName>
    <description>Captures  logic expression  using the fileds of the defined rule criteria as operands ( rule criteria ) For Example : if a rule had 3 criteria : Criteria 1 ( Industry  =   &apos;Banking&apos; ) , Criteria 2 (Country=&apos;United States&apos;) , Criteria 3 (Type=&apos;Active&apos;  ) the Display Filter logic for  : Criteria  1 AND Criteria  2 OR Criteria  3   would be   Industry  =   &apos;Banking&apos; AND Country=&apos;United States&apos; OR Type=&apos;Active&apos;
During save the DisplayfilterLogic is calculated based on the value captured on  the Filter_Logic value ( 1 AND 2 OR 3 ) The calcuation derives the field name of the rule criteria  for the positional operators. The field is used for display purposes  to the user</description>
    <label>Rule Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Evaluation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Rule__c</fullName>
    <label>Evaluation Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </value>
            <value>
                <fullName>Record is created</fullName>
            </value>
            <value>
                <fullName>Record is created or edited</fullName>
            </value>
            <value>
                <fullName>On Click Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Execution_Behavior__c.field-meta.xml
<CustomField>
    <fullName>Execution_Behavior__c</fullName>
    <label>Execution Behavior</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Execute Rule and Continue to Next Rule</fullName>
            </value>
            <value>
                <fullName>Execute Rule and Exit</fullName>
                <default>true</default>
                <label>Execute Rule and Exit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_Logic__c</fullName>
    <description>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</description>
    <inlineHelpText>Captures the logic based on position of the rule criteria For Example : if a rule had 3 criteria : Criteria 1, Criteria 2, Criteria 3  the Filter logic could be : 1 AND 2 OR 3</inlineHelpText>
    <label>Filter Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Archive__c/Rule_Archive__c.object-meta.xml
<CustomObject>
    <label>Rule Archive</label>
    <nameField>
        <displayFormat>RArc{000000}</displayFormat>
        <label>Rule Archive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Archive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Archive__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rule_Archive__c/fields/Evaluation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Rule__c</fullName>
    <label>Evaluation Rule</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Archive__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Archived&apos;</defaultValue>
    <description>Captures the Status of the Rule</description>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/RuleAction__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RuleAction__c/fields/Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Template__c</fullName>
    <label>Email Template</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ccount Name</fullName>
            </value>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Site</fullName>
            </value>
            <value>
                <fullName>Account Source</fullName>
            </value>
            <value>
                <fullName>Annual Revenue</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Created By</fullName>
            </value>
            <value>
                <fullName>Data.com Key</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Last Modified By</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Parent Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>SIC Code</fullName>
            </value>
            <value>
                <fullName>SIC Description</fullName>
            </value>
            <value>
                <fullName>Ticker Symbol</fullName>
            </value>
            <value>
                <fullName>Type</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Long_Value__c.field-meta.xml
<CustomField>
    <fullName>Long_Value__c</fullName>
    <label>Long Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Update Field</fullName>
                <default>true</default>
                <label>Update Field</label>
            </value>
            <value>
                <fullName>Insert Related Object</fullName>
            </value>
            <value>
                <fullName>Insert Classification</fullName>
                <color>#FF0000</color>
                <label>Insert Classification</label>
            </value>
            <value>
                <fullName>Send Email</fullName>
            </value>
            <value>
                <fullName>Execute an Apex Job</fullName>
            </value>
            <value>
                <fullName>Apex Callout-HTTP</fullName>
            </value>
            <value>
                <fullName>Load Iframe</fullName>
            </value>
            <value>
                <fullName>Load a VF Page</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Attach Documents</fullName>
            </value>
            <value>
                <fullName>Chatter Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/RuleCriteria__c.object-meta.xml
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <label>Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RuleCriteria__c/fields/CrossFormula__c.field-meta.xml
<CustomField>
    <fullName>CrossFormula__c</fullName>
    <label>Cross Formula</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Matching_Type__c.field-meta.xml
<CustomField>
    <fullName>Matching_Type__c</fullName>
    <label>Matching Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not Equal To</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Does Not Contain</fullName>
            </value>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Ends With</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Greater Or Equal</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Less Or Equal</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
            <value>
                <fullName>Between</fullName>
            </value>
            <value>
                <fullName>Regular Expression</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Matching_Value__c.field-meta.xml
<CustomField>
    <fullName>Matching_Value__c</fullName>
    <label>Matching Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Criteria</relationshipLabel>
    <relationshipName>Rule_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Values_for_Action_Insert_Record__c/Values_for_Action_Insert_Record__c.object-meta.xml
<CustomObject>
    <description>Captures the values  for the Insert  Related Record Action</description>
    <label>Values for Action Insert Record</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Values for Action Insert Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Values_for_Action_Insert_Record__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value to be populated on field</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AW_RetrieveVersionController.cls
public with sharing class AW_RetrieveVersionController {
	
	static 	String xmlString 						=	null;
	static	AW_ParseXML_Rule_Helper 				wfRule				=	null;
	static	AW_ParseXML_Criteria_Helper		  		auxCriteria			=	null;
	static	AW_ParseXML_Action_Helper 				auxAction			=	null;	
	static	AW_ParseXML_RelatedAction_Helper		auxRelatedAction	=	null;	
	static	Integer 			ruleNumber 			=	0;
	public  Rule_Archive__c		ruleArchive			=	null;
	static	decimal				version			=	0;
	Static	String				objeto				=	null;

	public AW_RetrieveVersionController(){
	
		list<Rule_Archive__c> ruleArchive = [SELECT body__c,Version__c,Object__c FROM Rule_Archive__c WHERE id =: ApexPages.currentPage().getParameters().get('id')];
		
		if(!ruleArchive.isEmpty()){
			//System.debug('\n---->BODY: '+ruleArchive.Body__c);
			xmlString	=	ruleArchive[0].Body__c;
			version		=	ruleArchive[0].Version__c;
			objeto		=	ruleArchive[0].Object__c;
			parser();
		}
	
	}	

	public static String  parser(){
		
		DOM.Document doc 	= 	new DOM.Document();     
  		try {
    		doc.load(xmlString);    
    		DOM.XMLNode root = doc.getRootElement();
    		walkThrough(root);

    		//Testeando objeto auxiliar FRAN
    		System.debug('\n--->Descripcion object: '+wFRule);

    		return null;
    	}catch (System.XMLException e) {  // invalid XML
    		return e.getMessage();
		}
	}
	

	
	public static void retrieveRule(){
		
		integer exists = 0;
		//Comprobar si existe una Rule (on name) con estado Active o draft, 
		//Si existe poner estado draft y name = name + dateTime (seconds)
		list<Rule__c> rule = [SELECT Name,status__c 
						FROM Rule__c 
						WHERE Name =: wfRule.ruleName AND ( (status__c = 'Active') OR (status__c = 'Draft') )];
						
		if( !rule.isEmpty()){
			exists = 1;
		}

		if(wfRule != null){
				
			Rule__c ruleSF 					=   new Rule__c();
			if(exists == 0){
				ruleSF.Name						=	wfRule.ruleName;
			}else{
				ruleSF.Name						=	wfRule.ruleName+datetime.now();
			}
			ruleSF.Object__c				=	objeto;
			ruleSF.Description__c			=	wfRule.description;
			ruleSF.Evaluation_Rule__c		=	wfRule.evaluationRule;
			ruleSF.DisplayfilterLogic__c	=	wfRule.ruleCriteria;
			ruleSF.Order__c					=	wfRule.orderRule;
			ruleSF.Execution_Behavior__c	=	'';   					//wfRule.executionBehavior
			ruleSF.Filter_Logic__c			=	wfRule.filterLogic;
			ruleSF.Version__c				=	null;					//version		
			ruleSF.Status__c				=	'Draft';						
			insert ruleSF;
//			listaRulesInsert.add(ruleSF);
					
			//Se insertan listas de criteria
			if(!wfRule.criterias.isEmpty()){
				for(AW_ParseXML_Criteria_Helper cr : wfRule.criterias){	
					RuleCriteria__c criteria		=   new RuleCriteria__c();
					criteria.field_name__c			= 	cr.criteriaName;	
					criteria.CrossFormula__c		= 	cr.crossFormula;
					criteria.Matching_Type__c		=	cr.matchingType;
					criteria.Matching_Value__c		=	cr.matchingValue1;
					criteria.Maximum_Value__c		=	cr.maximumValue;
					criteria.Minimum_Value__c		=	cr.minimumValue;
					criteria.Related_Object__c		=	cr.criteriarelatedObject;
					criteria.Rule__c				=	ruleSF.id;
					insert criteria;
				}
			}
					
			//Se insertan las listas de action
			if(!wfRule.actions.isEmpty()){
				for(AW_ParseXML_Action_Helper ac : wfRule.actions){	
					RuleAction__c action	     	=   new RuleAction__c();
					action.Related_Object__c		=	ac.actionrelatedObject;
					action.Field_API_Name__c		=	ac.actionfieldAPIName;
					action.Type__c					=	ac.typeAction;
					action.Field_Name__c			=	ac.actionfieldName;
					action.Value__c					=	ac.actionvalue;
					action.Long_Value__c			=	ac.actionlongValue;
					action.Email_Template__c		=	ac.actionEmail_Template;
					action.EmailTemplateName__c 	=	ac.actionEmailTemplateName;
					action.CrossObjectField__c		=	ac.actionCrossObjectField;
					action.Field_Type__c			=	ac.actionField_Type;
					action.Reference_Id__c			=	ac.actionReference_Id;
					action.User_Owner_Id__c			=	ac.actionUser_Owner;
					action.Rule__c					=	ruleSF.Id;
					if(ac.actionnotifyUser == 'TRUE') action.Notify_User__c = true;
					insert action;
							
					//Se insertan las listas RelatedActions
					if(!ac.listaRAction.isEmpty()){
						for(AW_ParseXML_RelatedAction_Helper ra : ac.listaRAction){
							Values_for_Action_Insert_Record__c relatedAction	=   new Values_for_Action_Insert_Record__c();
							relatedAction.Rule_Action__c	=	action.id;
							relatedAction.Name				=	ra.FieldName;
							relatedAction.Value__c			=	ra.value;
							insert relatedAction;
						}								
					}
							
				}
						
			}					
		}
				
	}
	
	//Se mapea el XML en objeto auxliar WFAdvance
	public static void walkThrough(DOM.XMLNode node) {
		
 		String result = '\n';
  		if (node.getNodeType() == DOM.XMLNodeType.ELEMENT) {
  						
  			
  			/*---------SECCION RULE----------*/
  			if(node.getName() 		== 'RULE_NAME'){	
  				
  				ruleNumber++;			
  				wfRule				=	new AW_ParseXML_Rule_Helper();
  				wfRule.ruleNumber	=	ruleNumber;
  				wfRule.ruleName		=	node.getAttribute('name', null);
  			}
  			else if(node.getName() 	== 'RULE_DESCRIPTION'){
  				wfRule.description	=	node.getText();
  			}else if(node.getName() == 'ORDER' && node.getText()!='null' ){
  				wfRule.orderRule	=	integer.valueOf(node.getText());
  			}else if(node.getName() == 'EVALUATION_RULE'){
  				wfRule.evaluationRule	=	node.getText();
  			}else if(node.getName() == 'EXECUTION_BEHAVIOR'){
  				wfRule.executionBehavior	=	node.getText();
  			}else if(node.getName() == 'DISPLAYFILTERLOGIC'){
  				wfRule.ruleCriteria	=	node.getText();
  			}else if(node.getName() == 'FILTER_LOGIC'){
  				wfRule.filterLogic	=	node.getText();
  			}
  			
  			
  			/*----- CRITERIA SECTION-------------*/
  			else if(node.getName() == 'CRITERIA'){
  				auxCriteria			=	new AW_ParseXML_Criteria_Helper();
  				wfRule.criterias.add(auxCriteria);
  			}else if(node.getName() == 'RULE_CRITERIA_FIELD_NAME'){
  				auxCriteria.criteriaName	=	node.getText();
  			}else if(node.getName() == 'CrossFormula'){
  				auxCriteria.crossFormula	=	node.getText();
  			}else if(node.getName() == 'MATCHING_TYPE'){
  				auxCriteria.matchingType	=	node.getText();
  			}else if(node.getName() == 'MATCHING_VALUE'){
  				auxCriteria.matchingValue1	=	node.getText();
  			}else if(node.getName() == 'MAXIMUM_VALUE'){
  				auxCriteria.maximumValue	=	node.getText();
  			}else if(node.getName() == 'MINIMUM_VALUE'){
  				auxCriteria.minimumValue	=	node.getText();
  			}else if(node.getName() == 'RELATED_OBJECT_CRITERIA'){
  				auxCriteria.criteriarelatedObject	=	node.getText();
  			}    
  			
  			
  			/*---- ACTION SECTION   ------------*/
  			else if(node.getName() == 'ACTION'){
  				auxAction		=		new AW_ParseXML_Action_Helper();
  				wfRule.actions.add(auxAction);
  			}else if(node.getName() == 'RELATED_OBJECT_ACTION'){
  				auxAction.actionrelatedObject = node.getText();
  			}else if(node.getName() == 'ACTION_TYPE'){
  				auxAction.typeAction = node.getText();
  			}else if(node.getName() == 'Field_Name'){
  				auxAction.actionfieldName = node.getText();
  			}else if(node.getName() == 'VALUE_for_Update'){
  				auxAction.actionvalue = node.getText();
  			}else if(node.getName() == 'LONG_VALUE'){
  				auxAction.actionlongValue = node.getText();
  			}else if(node.getName() == 'NOTIFY_USER'){
  				auxAction.actionnotifyUser = node.getText();
  			}else if(node.getName() == 'REFERENCE_ID'){
  				auxAction.actionReference_Id = node.getText();
  			}else if(node.getName() == 'CROSSOBJECTFIELD'){
  				auxAction.actionCrossObjectField = node.getText();
  			}else if(node.getName() == 'ACTION_USER_OWNER'){
  				auxAction.actionUser_Owner = node.getText();
  			}else if(node.getName() == 'ACTION_FIELD_API_NAME'){
  				auxAction.actionfieldAPIName = node.getText();
  			}else if(node.getName() == 'EMAIL_TEMPLATE_NAME'){
  				auxAction.actionEmailTemplateName = node.getText();
  			}else if(node.getName() == 'EMAIL_TEMPLATE'){
  				auxAction.actionEmail_Template = node.getText();
  			}else if(node.getName() == 'EMAIL_TEMPLATE'){
  				auxAction.actionEmail_Template = node.getText();
  			}
  			
  			
  			/*----SECCION RELATEDOBJECT-ACTION--*/
  			else if(node.getName() == 'Insert_Field'){
  				system.debug('>>Insert_Field'+ node.getName());
  				auxRelatedAction	=	new AW_ParseXML_RelatedAction_Helper();
  				auxAction.listaRAction.add(auxRelatedAction);
  			}else if(node.getName() == 'Field_Name_Insert'){
  				system.debug('>>Insert_Field'+ node.getName());
  				system.debug('>>Insert_Field'+ node.getText());
  				auxRelatedAction.fieldName = node.getText();
  			}else if(node.getName() == 'Value_For_Insert'){
  				auxRelatedAction.value = node.getText();
  				system.debug('>>Insert_Field'+ node.getText());
  			}
  			
		    for (Dom.XMLNode child: node.getChildElements()) {
		      walkThrough(child);
		    }
		    		    
	  	}
 	  	
	}

	@isTest
	static void MyTest() {
		
				 String body = 		'<RULE_NAME name="Account Rule NAME B">'+
									'<RULE_DESCRIPTION>DESCRIPTION FIELD SAMPLE ACOUNT RULE WITH 2 FILTER CRITERIA AND 6 ACTION</RULE_DESCRIPTION>'+
									'<AVAILABLE>True</AVAILABLE>'+
									'<ORDER>0</ORDER>'+
									'<EVALUATION_RULE>"Record is created or edited and did not previously meet the rule criteria"</EVALUATION_RULE>'+
									'<EXECUTION_BEHAVIOR>null</EXECUTION_BEHAVIOR>'+
									'<DISPLAYFILTERLOGIC>Account.CrossFormula = Inside Sales AND Account.BillingCountry != USA</DISPLAYFILTERLOGIC>'+
									'<FILTER_LOGIC>null</FILTER_LOGIC>'+
									'<RULE_CRITERIA_SECTION>'+
									'<CRITERIA num="1">'+
									'<RULE_CRITERIA_FIELD_NAME>"CrossFormula"</RULE_CRITERIA_FIELD_NAME>'+
									'<CrossFormula>null</CrossFormula>'+
									'<MATCHING_TYPE>"Equals"</MATCHING_TYPE>'+
									'<MATCHING_VALUE>"Inside Sales"</MATCHING_VALUE>'+
									'<MAXIMUM_VALUE>null</MAXIMUM_VALUE>'+
									'<MINIMUM_VALUE>null</MINIMUM_VALUE>'+
									'<RELATED_OBJECT_CRITERIA>null</RELATED_OBJECT_CRITERIA>'+
									'</CRITERIA>'+
									'<CRITERIA num="2">'+
									'<RULE_CRITERIA_FIELD_NAME>"BillingCountry"</RULE_CRITERIA_FIELD_NAME>'+
									'<CrossFormula>null</CrossFormula>'+
									'<MATCHING_TYPE>"Equals"</MATCHING_TYPE>'+
									'<MATCHING_VALUE>"Inside Sales"</MATCHING_VALUE>'+
									'<MAXIMUM_VALUE>null</MAXIMUM_VALUE>'+
									'<MINIMUM_VALUE>null</MINIMUM_VALUE>'+
									'<RELATED_OBJECT_CRITERIA>"Opp"</RELATED_OBJECT_CRITERIA>'+
									'</CRITERIA>'+
									'</RULE_CRITERIA_SECTION>'+
									'<RULE_ACTION_SECTION>'+
									'<ACTION num="1">'+
									'<RELATED_OBJECT_ACTION>null</RELATED_OBJECT_ACTION>'+
									'<ACTION_TYPE>null</ACTION_TYPE>'+
									'<Field_Name>null</Field_Name>'+
									'<VALUE_for_Update>null</VALUE_for_Update>'+
									'<LONG_VALUE>null</LONG_VALUE>'+
									'<NOTIFY_USER>false</NOTIFY_USER>'+
									'<EMAIL_TEMPLATE>null</EMAIL_TEMPLATE>'+
									'</ACTION>'+
									'<ACTION num="2">'+
									'<RELATED_OBJECT_ACTION>null</RELATED_OBJECT_ACTION>'+
									'<ACTION_TYPE>null</ACTION_TYPE>'+
									'<Field_Name>null</Field_Name>'+
									'<VALUE_for_Update>null</VALUE_for_Update>'+
									'<LONG_VALUE>null</LONG_VALUE>'+
									'<NOTIFY_USER>false</NOTIFY_USER>'+
									'<EMAIL_TEMPLATE>null</EMAIL_TEMPLATE>'+
									'<INSERT_RELATED_OBJECT_SECTION>'+
									'<Insert_Field>1</Insert_Field>'+
									'<Field_Name_Insert>"LastName"</Field_Name_Insert>'+
									'<Value_For_Insert>"Barr"</Value_For_Insert>'+
									'<Insert_Field>2</Insert_Field>'+
									'<Field_Name_Insert>"Department"</Field_Name_Insert>'+
									'<Value_For_Insert>"Finance"</Value_For_Insert>'+
									'</INSERT_RELATED_OBJECT_SECTION>'+
									'</ACTION>'+
									'</RULE_ACTION_SECTION>'+
									'</RULE_NAME>';				

	
		Rule_Archive__c ruleArchive =  new Rule_Archive__c(Object__c = 'account');
		ruleArchive.Body__c	= body;
		insert ruleArchive;	
		
		PageReference pageRef = Page.AW_RetrieveVersion_VF;
		Test.setCurrentPage(pageRef);
		
		pageRef.getParameters().put('id', ruleArchive.id);
		
	 	AW_RetrieveVersionController retrieveVersion1	=	new AW_RetrieveVersionController();
	 	
	 	AW_RetrieveVersionController.xmlString = body;
	 	     
        Rule__c rule	=	new Rule__c(Name = 'Account Rule NAME B',status__c = 'Active',version__c = 1,description__c = 'descripcion',
        								Evaluation_Rule__c='evaluation',Object__c='account');
       	insert rule;	 
       	
        AW_RetrieveVersionController.retrieveRule();
       		
	 	
	}	
	
}