force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Evaluation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Rule__c</fullName>
    <label>Evaluation Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </value>
            <value>
                <fullName>Record is created</fullName>
            </value>
            <value>
                <fullName>Record is created or edited</fullName>
            </value>
            <value>
                <fullName>On Click Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/RuleAction__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RuleAction__c/fields/CrossObjectField__c.field-meta.xml
<CustomField>
    <fullName>CrossObjectField__c</fullName>
    <inlineHelpText>Cross Object Field Notation :  Relationshipname.FieldName. Eg:- Account.Type</inlineHelpText>
    <label>Cross Object Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Template__c</fullName>
    <label>Email Template</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ccount Name</fullName>
            </value>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Site</fullName>
            </value>
            <value>
                <fullName>Account Source</fullName>
            </value>
            <value>
                <fullName>Annual Revenue</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Created By</fullName>
            </value>
            <value>
                <fullName>Data.com Key</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Last Modified By</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Parent Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>SIC Code</fullName>
            </value>
            <value>
                <fullName>SIC Description</fullName>
            </value>
            <value>
                <fullName>Ticker Symbol</fullName>
            </value>
            <value>
                <fullName>Type</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Update Field</fullName>
                <default>true</default>
                <label>Update Field</label>
            </value>
            <value>
                <fullName>Insert Related Object</fullName>
            </value>
            <value>
                <fullName>Insert Classification</fullName>
                <color>#FF0000</color>
                <label>Insert Classification</label>
            </value>
            <value>
                <fullName>Send Email</fullName>
            </value>
            <value>
                <fullName>Execute an Apex Job</fullName>
            </value>
            <value>
                <fullName>Apex Callout-HTTP</fullName>
            </value>
            <value>
                <fullName>Load Iframe</fullName>
            </value>
            <value>
                <fullName>Load a VF Page</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Attach Documents</fullName>
            </value>
            <value>
                <fullName>Chatter Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/User_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Owner_Id__c</fullName>
    <label>User/Owner Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AW_SendEmailUtil_Test.cls
//
// (c) 2012 Appirio, Inc.
//
//  AW_SendEmailUtil_Test
//
// This class contains test methods for Testing sendEmailUtil functionality
//
// 10 Oct 2012     Peter Babalis          Original
// 11 Nov 2012     Sneha                  Templates
//
@isTest
public class AW_SendEmailUtil_Test{

    /**
    * Test sendEmail method
    */
    public static TestMethod void SendEmailUtil_Test(){
        Test.startTest();
        new AW_SendEmailUtil().sendEmail(new List<string>{'test@test.com'}, new List<String>{'test test'});
        Test.stopTest();
        //System.assertNotEquals(0,Limits.getEmailInvocations());
    }

   public  static TestMethod void sendEmailTest3() {
        Account a = new Account(Name = 'test');
        insert a;
        Attachment att = new Attachment();
        att.Body = Blob.valueOf('test');
        att.Name = 'test.xml';
        att.ParentId = a.Id;
        insert att;
        Test.startTest();
        AW_SendEmailUtil.sendEmailwithAttachment(att);
        Test.stopTest();
    }

    @isTest(SeeAllData=true)
    public static void sendEmailTest2(){
        EmailTemplate e=[Select Id,Body FROM EmailTemplate LIMIT 1];
        /*START -- Commented by Mohit Tanwar | Case #00278177 |[14-05-2020] | [Updating test data to resolve batch error]*/
        //Rule__c rule = AW_AdvanceWorkflowExecutionEngine_Test.setupRules();
        /*END-- Commented by Mohit Tanwar | Case #00278177 |[14-05-2020] | [Updating test data to resolve batch error]*/
   		/*START -- Added by Mohit Tanwar | Case #00278177 |[14-05-2020] | [Updating test data to resolve batch error]*/
            Rule__c rule = new Rule__c(Name = 'Test Test Account',Object__c = 'Account', Status__c='Draft',Evaluation_Rule__c='Record is created or edited',Description__c='Rule 1 Description');
        /*END -- Added by Mohit Tanwar | Case #00278177 |[14-05-2020] | [Updating test data to resolve batch error]*/     
        insert rule;    
        
        RuleAction__c a1 = new RuleAction__c(rule__c=rule.id,related_object__c='Contact',
                                                            field_name__c='CrossObject',CrossObjectField__c='Account.Type',Type__c='Send Email',User_Owner_Id__c=UserInfo.getUserId(),Email_Template__c=e.Id);
        insert a1;

        User u=[Select Id,Name,FirstName,Lastname,email FROM User WHERE Id =:UserInfo.getUserId()];
        Map<Id,User> user = new Map<Id,User>();
        user.put(u.Id,u);

        System.runAs(u) {
          Account a = new Account(Name='testing 11/4/2013123456');
          insert a;
		  /*START -- Commented by Mohit Tanwar | Case #00278177 |[15-05-2020] | [Updating test data to resolve batch error]*/
          //Contact c = new Contact (LeadSource='NGL',MailingCountry='USA',MailingState='TX',MailingCity='Dallas', FirstName='firstname',Salutation='Mr.',LastName='test123456',email='test123456@test123456.com');
          //insert c;
            
           //Lead l = new Lead (LastName='test1234567',Company='test',email='test1234567@test1234567.com');
          //insert l;
          /*END-- Commented by Mohit Tanwar | Case #00278177 |[15-05-2020] | [Updating test data to resolve batch error]*/  
          //Map
          Map<String,Map<String,List<RuleAction__c>>> userEmailInfo= new Map<String,Map<String,List<RuleAction__c>>>();
          Map<String,List<RuleAction__c>> data = new Map<String,List<RuleAction__c>>();
          data.put(a.Id,new List<RuleAction__c>{a1 });
           /*START -- Commented by Mohit Tanwar | Case #00278177 |[15-05-2020] | [Updating test data to resolve batch error]*/ 
          //data.put(c.Id,new List<RuleAction__c>{a1 });
          //data.put(l.Id,new List<RuleAction__c>{a1 });
          /*END-- Commented by Mohit Tanwar | Case #00278177 |[15-05-2020] | [Updating test data to resolve batch error]*/
          userEmailInfo.put(u.Id,data);
          Test.startTest();
            try{
                new AW_SendEmailUtil().sendEmail(user, userEmailInfo);
           }catch(Exception ex){
               system.debug(ex);
           }
          Test.stopTest();
        }


    }
}