force-app/main/default/objects/Deal_Sheet__c/Deal_Sheet__c.object-meta.xml
<CustomObject>
    <label>Deal Sheet</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Deal Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Sheet__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <summarizedField>Deal_Sheet_Line_Item__c.End_Date__c</summarizedField>
    <summaryForeignKey>Deal_Sheet_Line_Item__c.Deal_Sheet__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Deal Sheet Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <summarizedField>Deal_Sheet_Line_Item__c.Start_Date__c</summarizedField>
    <summaryForeignKey>Deal_Sheet_Line_Item__c.Deal_Sheet__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/Deal_Sheet_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Deal Sheet Line Item</label>
    <nameField>
        <displayFormat>DSLI-{000000}</displayFormat>
        <label>Deal Sheet Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Sheet Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Calendar_Day__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Day__c</fullName>
    <description>This field is created as a replica of calendar Workdays</description>
    <label>Calendar Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Deal_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Deal_Sheet__c</fullName>
    <label>Deal Sheet</label>
    <referenceTo>Deal_Sheet__c</referenceTo>
    <relationshipLabel>Deal Sheet Line Items</relationshipLabel>
    <relationshipName>Deal_Sheet_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateDealSheetCalendarDaysBatchTest.cls
/*********************************************************************************
Name : Harendra Sain
Created By : Appirio  
Created Date : 13 Jan. 2016
Purpose : Renewal Oppty Batch test class
*********************************************************************************/
@IsTest
private with sharing class UpdateDealSheetCalendarDaysBatchTest {
    static testMethod void UpdateDealSheetCalendarMethod (){
      Deal_Sheet__c dc = new Deal_Sheet__c();
      dc.Project_Name__c = 'testing';     
      insert dc;
      
        Deal_Sheet_Line_Item__c dsli = new  Deal_Sheet_Line_Item__c ();
        dsli.Deal_Sheet__c = dc.id;        
        dsli.Start_Date__c = date.today();
        dsli.End_Date__c = date.today().adddays(10);
        Integer numberDaysDue = dsli.Start_Date__c.daysBetween(dsli.End_Date__c);
        dsli.Calendar_Day__c = numberDaysDue;
        insert dsli;
        
        UpdateDealSheetCalendarDaysBatch uc = new UpdateDealSheetCalendarDaysBatch();
		    Test.startTest();
		    Database.executeBatch(uc);
		    Test.stopTest();
    }
    
    static testMethod void CalculateDays (){
       DateTime startDateTime = DateTime.newInstance(2008, 1, 1, 0, 0, 0);
       DateTime enddateTime = DateTime.newInstance(2008, 1, 30, 0, 0, 0);
       Date startDate = date.newinstance(startDateTime.year(), startDateTime.month(), startDateTime.day());
       Date endDate = date.newinstance(enddateTime.year(), enddateTime.month(), enddateTime.day());

       Integer numberDaysDue = startDate.daysBetween(enddate);
 system.debug('==========+++===='+numberDaysDue);
      System.assert(numberDaysDue == 29); 
     
    }

}