force-app/main/default/objects/Deal_Sheet__c/Deal_Sheet__c.object-meta.xml
<CustomObject>
    <label>Deal Sheet</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Deal Sheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Sheet__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <summarizedField>Deal_Sheet_Line_Item__c.End_Date__c</summarizedField>
    <summaryForeignKey>Deal_Sheet_Line_Item__c.Deal_Sheet__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Deal Sheet Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <summarizedField>Deal_Sheet_Line_Item__c.Start_Date__c</summarizedField>
    <summaryForeignKey>Deal_Sheet_Line_Item__c.Deal_Sheet__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/Deal_Sheet_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Deal Sheet Line Item</label>
    <nameField>
        <displayFormat>DSLI-{000000}</displayFormat>
        <label>Deal Sheet Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Sheet Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Billable_Days__c.field-meta.xml
<CustomField>
    <fullName>Billable_Days__c</fullName>
    <label>Billable Days</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Daily_Bill_Rate__c.field-meta.xml
<CustomField>
    <fullName>Daily_Bill_Rate__c</fullName>
    <inlineHelpText>Suggested Rates:
Managing Director:  3,000 
Senior Director:  2,883 
Director:  2,235 
Associate Director:  1,767 
Associate Consultant:  1,333 
Business Analyst:  1,112 
IC:  2,000</inlineHelpText>
    <label>Daily Bill Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Daily_Cost_Rate__c.field-meta.xml
<CustomField>
    <fullName>Daily_Cost_Rate__c</fullName>
    <label>Daily Cost Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Deal_Sheet__c.field-meta.xml
<CustomField>
    <fullName>Deal_Sheet__c</fullName>
    <label>Deal Sheet</label>
    <referenceTo>Deal_Sheet__c</referenceTo>
    <relationshipLabel>Deal Sheet Line Items</relationshipLabel>
    <relationshipName>Deal_Sheet_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Fixed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Revenue__c</fullName>
    <label>Fixed Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Type__c</fullName>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Resource</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Sheet_Line_Item__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>President</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Vice President</fullName>
            </value>
            <value>
                <fullName>Senior Director</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Associate Director</fullName>
            </value>
            <value>
                <fullName>Associate Consultant</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>Independent Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MaintainReportBalanceOnDealSheetTest.cls
/*******************************************************************************
* @Class       : MaintainReportBalanceOnDealSheetTest
* @author      : Rohit
* @description : Test Class of Batch_MaintainReportBalanceOnDealSheet (S-635394)
*******************************************************************************/
@isTest
public class MaintainReportBalanceOnDealSheetTest {
    public static testMethod void testBatchUpdatePaidDateSI() {
        Deal_Sheet__c ds = new Deal_Sheet__c();
        ds.Project_Name__c = 'testproj';
        insert ds;
        
        Deal_Sheet_Line_Item__c dlsi = new Deal_Sheet_Line_Item__c();
        dlsi.Line_Type__c = 'Resource';
        dlsi.Role__c = 'Independent Contractor';
        dlsi.Start_Date__c = Date.today();
        dlsi.End_Date__c = Date.today().addMonths(1);
        dlsi.Billable_Days__c = 1;
        dlsi.Daily_Cost_Rate__c = 12;
        dlsi.Daily_Bill_Rate__c = 12;
        dlsi.Fixed_Revenue__c = 12;
        dlsi.Deal_Sheet__c = ds.id;
        insert dlsi;
        
        List<c2g__ReportingBalance__c> lstRB = new List<c2g__ReportingBalance__c>([select id from c2g__ReportingBalance__c where Deal_Sheet__c = :ds.id]);

        Deal_Sheet_Line_Item__c dlsi2 = new Deal_Sheet_Line_Item__c();
        dlsi2.Line_Type__c = 'Resource';
        dlsi2.Role__c = 'Director';
        dlsi2.Start_Date__c = Date.today();
        dlsi2.End_Date__c = Date.today().addMonths(10);
        dlsi2.Billable_Days__c = 6;
        dlsi2.Daily_Cost_Rate__c = 12;
        dlsi2.Daily_Bill_Rate__c = 12;
        dlsi2.Fixed_Revenue__c = 12;
        dlsi2.Deal_Sheet__c = ds.id;
        insert dlsi2;
        
        List<c2g__ReportingBalance__c> lstRB1 = new List<c2g__ReportingBalance__c>([select id from c2g__ReportingBalance__c where Deal_Sheet__c = :ds.id and c2g__GeneralLedgerAccount__c = 'a1dF0000000BXfm']);
        
        Test.startTest();
        Batch_MaintainReportBalanceOnDealSheet btch = new Batch_MaintainReportBalanceOnDealSheet();
        Database.executeBatch(btch);
        Test.stopTest();
    }
}