force-app/main/default/objects/Event_Members__c/Event_Members__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Members__c/fields/Day_1_Role__c.field-meta.xml
<CustomField>
    <fullName>Day_1_Role__c</fullName>
    <label>Day 1 Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited Member</fullName>
            </value>
            <value>
                <fullName>Invited Advisor</fullName>
            </value>
            <value>
                <fullName>Invited Prospect</fullName>
            </value>
            <value>
                <fullName>Invited Speaker</fullName>
            </value>
            <value>
                <fullName>Invited Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Session Chair</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>CHRO - Not Attending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Invited</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Members__c/fields/Day_2_Role__c.field-meta.xml
<CustomField>
    <fullName>Day_2_Role__c</fullName>
    <label>Day 2 Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited Member</fullName>
            </value>
            <value>
                <fullName>Invited Advisor</fullName>
            </value>
            <value>
                <fullName>Invited Prospect</fullName>
            </value>
            <value>
                <fullName>Invited Speaker</fullName>
            </value>
            <value>
                <fullName>Invited Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Session Chair</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>CHRO - Not Attending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Invited</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Member Designate</fullName>
            </value>
            <value>
                <fullName>Not Attending - Sent Designate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Members__c/fields/Day_3_Role__c.field-meta.xml
<CustomField>
    <fullName>Day_3_Role__c</fullName>
    <description>Role of the attendee on day three (applies to Women&apos;s Leadership Acceleration)</description>
    <label>Day 3 Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited Member</fullName>
            </value>
            <value>
                <fullName>Invited Advisor</fullName>
            </value>
            <value>
                <fullName>Invited Prospect</fullName>
            </value>
            <value>
                <fullName>Invited Speaker</fullName>
            </value>
            <value>
                <fullName>Invited Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Session Chair</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>CHRO - Not Attending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CountNumberOfAttendee.cls
/*********************************************************************************
Name : Nitin Vyas
Created By : Appirio  
Created Date : 27 Nov 2018
Purpose : it is a batch class for Counting Number of Attendee
*********************************************************************************/
global class CountNumberOfAttendee implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('Select Id,Name,Account_Name__c,(Select Day_1_Role__c,	Day_2_Role__c,Day_3_Role__c,Event_End_Date__c from Event_Members__r where Event_End_Date__c !=null) From Contact');
        
    }
    
    global void execute(Database.BatchableContext BC,List<Contact> conLst) {
        Map<Id,Integer> eventMap = new Map<Id,Integer>();
        List<Id> conId = new List<Id>();
        List<Id> eveId = new List<Id>();
        List<Contact> conLstWthNumber = new List<Contact>();
        for(Contact contactLst : conLst) {
            for(Event_Members__c em : contactLst.Event_Members__r) {
                if((em.Event_End_Date__c > (Date.today()-395) && em.Event_End_Date__c <= (Date.today())) &&
                   ((em.Day_1_Role__c=='Guest' || 
                     em.Day_1_Role__c=='Prospect' ||
                     em.Day_1_Role__c=='Member' ||
                     em.Day_1_Role__c=='Advisor') ||
                    (em.Day_2_Role__c=='Guest' || 
                     em.Day_2_Role__c=='Prospect' ||
                     em.Day_2_Role__c=='Member' ||
                     em.Day_2_Role__c=='Advisor') ||
                    em.Day_3_Role__c=='Guest' || 
                    em.Day_3_Role__c=='Prospect' ||
                    em.Day_3_Role__c=='Member' ||
                    em.Day_3_Role__c=='Advisor')){
                        
                        if(!eventMap.containsKey(contactLst.Id)) {
                            eventMap.put(contactLst.Id,1);
                        }
                        else {
                            Integer count = eventMap.get(contactLst.Id);
                            count = count+1;
                            eventMap.put(contactLst.Id,count);
                        }
                    }
            }     
        }
        
        for(Id conIdVal : eventMap.keySet()) {
            System.debug('>>>conId>>>'+conIdVal);
            System.debug('>>>Count>>>'+eventMap.get(conIdVal));
            Contact con = new Contact();
            con.Id=conIdVal;
            con.Number_of_meetings_Attended__c = eventMap.get(conIdVal);
            conLstWthNumber.add(con);
        }
        
        if(conLstWthNumber!=null && !conLstWthNumber.isEmpty()) {
            update conLstWthNumber;
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}