force-app/main/default/objects/Advance_Workflow__c/Advance_Workflow__c.object-meta.xml
<CustomObject>
    <description>This object holds the definition of the workflows for standard and custom objects</description>
    <label>Advance Workflow</label>
    <nameField>
        <label>Advance Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advance Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance_Workflow__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Holds the description of the Workflow</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Advance_Workflow__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</description>
    <inlineHelpText>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advance_Workflow_Available_objects__c/Advance_Workflow_Available_objects__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Advance Workflow for case # : - 00142114</description>
    <label>Advance Workflow Available objects</label>
</CustomObject>

force-app/main/default/objects/Advance_Workflow_Available_objects__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>API name of the object that you wish to add in custom setting.</description>
    <inlineHelpText>API name of the object that you wish to add in custom setting.</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Advance_Workflow_Available_objects__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this checkbox if you wish to keep the object as available to create Advance workflow.</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Advance_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Advance_Workflow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance Workflow</label>
    <referenceTo>Advance_Workflow__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Evaluation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Rule__c</fullName>
    <label>Evaluation Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </value>
            <value>
                <fullName>Record is created</fullName>
            </value>
            <value>
                <fullName>Record is created or edited</fullName>
            </value>
            <value>
                <fullName>On Click Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Total_Actions__c.field-meta.xml
<CustomField>
    <fullName>Total_Actions__c</fullName>
    <label>Total Actions</label>
    <summaryForeignKey>RuleAction__c.Rule__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Total_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Total_Criteria__c</fullName>
    <label>Total Criteria</label>
    <summaryForeignKey>RuleCriteria__c.Rule__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/AW_RuleController.cls
// 
// (c) 2012 Appirio, Inc.
//
//  AW_RuleController	                                                  
//
// This class is used for creating and editing Rule
//
// 31 Aug 2012     Peter Babalis     Original
//  
//
/*
If active---> RO (object, evaluation rule,rule name ,Description,  ), Status can go to archive or Draft  

If Status = Draft (edit=false )---> Status, object, evaluation, Description , rule name  Status can go to  Archive …to activate the rule use the “add rule to workflow”

If Archive ---> RO (object, evaluation rule,rule name  Description,) Status Status can go to Draft  if there is a rule on Draft override the existing rule from archive 

*/
public with sharing class AW_RuleController{
    public Rule__c newrule     {get;set;}  
    public String objType   {get;set;}
    public string SearchEvalRule {get;set;}
    public string SearchStatusRule {get;set;}
    public Integer Version {get;set;}
 //   public string StatusRule {get;set;}
    public string Descr {get;set;}
    public List<SelectOption> objOptions    {get;set;}
   
    public boolean edit {get;set;}
    
    public boolean editrule {get;set;}
    public boolean edistatus {get;set;}
    public boolean editdescr {get;set;}
    public boolean editobject {get;set;}
    public boolean editevalrule {get;set;}
    
     		
    
     
    String ruleId;
    
    public AW_RuleController(Apexpages.StandardController stdcon){
        ruleId = stdcon.getId();
        newrule = new Rule__c();
        objOptions = new List<SelectOption>();
        
        /* Start */
      /* Modified by Gaurav Dudani on 4th December 2015 for case # 00142114  */
      
        If(Advance_Workflow_Available_objects__c.getAll() != null) {
        List<Advance_Workflow_Available_objects__c> advWorkFlowRules = new  List<Advance_Workflow_Available_objects__c>();
        advWorkFlowRules =  Advance_Workflow_Available_objects__c.getAll().values();
        if(advWorkFlowRules.size() > 0) {
        Set<String> objAPI = new Set<String>();
        for(Advance_Workflow_Available_objects__c obj:Advance_Workflow_Available_objects__c.getAll().values()){
            if(obj.Available__c){
                objAPI.add(obj.API_Name__c); // to add the api names to the set.
            }
        } 
        
        
        if(objAPI.size()>0){
        /* End */
             
        Map<String, Schema.SObjectType> mapObj = Schema.getGlobalDescribe();
        for(String objname:mapObj.keySet()){
            Schema.SObjectType sobj = mapObj.get(objname);
            Schema.DescribeSObjectResult descRes = sobj.getDescribe();
            if(!descRes.isCustomSetting() && descRes.isAccessible() && (descRes.isCreateable() || descRes.isUpdateable())){
                 String objLabel = descRes.getLabel();
         /* Start */
        /* Modified by Gaurav Dudani on 9th December 2015 for case # 00142114  */
                if(objAPI.contains(descRes.getName())){
        /* End */
                 objOptions.add(new SelectOption(descRes.getName(),objLabel + ' (' + descRes.getName() + ')'));
               // proposed String objName = descRes.getName();
               // proposed    objOptions.add(new SelectOption(descRes.getLabel(),objLabel + ' (' + descRes.getName() + ')'));
                }
               }
         /* Start */
        /* Modified by Gaurav Dudani on 9th December 2015 for case # 00142114  */
              }
             }
        	} 	
           }
        /* End */
         objOptions.sort();
  
         /* Edit Rule */
       if(ruleId!=null){
            edit=true;
            newrule = [SELECT  name,
                               Object__c,
                               Advance_Workflow__c,
                               Status__c,
                               Version__c,
                               Evaluation_Rule__c,
                               Description__c ,
                               Total_Actions__c,
                               Total_Criteria__c
                       FROM    Rule__c
                       WHERE   id=:ruleId];
            if(newrule!=null){
                objtype=newrule.Object__c;
                Descr =newrule.Description__c;
                Version=integer.valueOf(newrule.Version__c);
                SearchEvalRule =newrule.Evaluation_Rule__c ;
                SearchStatusRule=newrule.Status__c ;
                /*
              If active or archive ---> RO (object, evaluation rule,rule name ,Description,  ), Status can go to archive or Draft  
              
              */ 
               if (SearchStatusRule =='Active' || SearchStatusRule =='Archived') { 
               	    editrule =false; 
                    editdescr=false; 
                    editobject =false;
                    editevalrule=false;
                    edistatus=true;
              }
               
               if (SearchStatusRule =='Draft' && newrule.Total_Criteria__c >0   && newrule.Total_Actions__c >0) { 
               	    editrule =true; 
                    editdescr=true; 
                    editobject =true;
                    editevalrule=true;
                    edistatus=true;
              } else if (SearchStatusRule =='Draft' && ( newrule.Total_Criteria__c ==0  ||  newrule.Total_Actions__c == 0)) { 
               	    editrule =true; 
                    editdescr=true; 
                    editobject =true;
                    editevalrule=true;
                    edistatus=false;
              
              }
              
              }
        } 
        else {
     
              editrule =true; 
              editdescr=true; 
              editobject =true;
              editevalrule=true;
              SearchStatusRule='Draft';
         	  Version=1;
        	   	   
         }
    }
   
   Public List<SelectOption> getStatusRule()  {
  
         List<selectOption> options = new List<selectOption>();
         Schema.DescribeFieldResult field = Rule__c.Status__c.getDescribe();
           /*
            for (Schema.Picklistentry picklistEntry : field.getPicklistValues())
               {
                    options.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
               }    
           */
            // options.add(new selectOption('Draft', 'Draft'));
            //  options.add(new selectOption('Archive', 'Archive'));
            if (SearchStatusRule =='Draft' ) {
            	  options.add(new selectOption('Draft', 'Draft'));
                  options.add(new selectOption('Archived', 'Archived'));
            }
            if (SearchStatusRule =='Active') {
                 options.add(new selectOption('Active', 'Active'));
                 options.add(new selectOption('Draft', 'Draft'));
                 options.add(new selectOption('Archived', 'Archived'));
            }
            if (SearchStatusRule =='Archived') {
            	options.add(new selectOption('Archived', 'Archived'));
                options.add(new selectOption('Draft', 'Draft'));
            }
             return options;  
   }  
  
  Public List<SelectOption> getEvalRule()  {
  
         List<selectOption> options = new List<selectOption>();
            options.add(new selectOption('', '- None -'));
            Schema.DescribeFieldResult field = Rule__c.Evaluation_Rule__c.getDescribe();
            for (Schema.Picklistentry picklistEntry : field.getPicklistValues())
               {
                    options.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
               }
           return options;  
   }  
   
    public PageReference saveRule(){
        newrule.object__c = objtype;
        newrule.Status__c =SearchStatusRule;
        newrule.Evaluation_Rule__c=SearchEvalRule;
        newrule.Description__c= Descr;
        newrule.Version__c= Version;
 
        try{
            Database.upsert(newrule);
          
           if (newrule.Status__c =='Archived' && newrule.Total_Criteria__c> 0 && newrule.Total_Actions__c >0 ) { 
              //Get a reference to the Custom Object and gets its Key
               Schema.DescribeSObjectResult result = Rule__c.sObjectType.getDescribe();
               //system.debug( 'result.getKeyPrefix() '+result.getKeyPrefix());
               PageReference pageRef = New PageReference('/' + result.getKeyPrefix() + '/o');
               pageRef.setRedirect(true);
               return pageRef;        
           }
           else  return(new PageReference('/'+newrule.id ));
          }
        catch(Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.Error,e.getDMLMessage(0));
            ApexPages.addMessage(msg);
            return null;
        }
        
    }
    
    public PageReference saveAndNewRule(){
         newrule.object__c = objtype;
         newrule.Evaluation_Rule__c=SearchEvalRule;
         newrule.Description__c= Descr;
         newrule.status__c ='Draft';
         newrule.Version__c= 1;
         //editrule =false; 
         //editdescr=false; 
        // editobject =false;
        // editevalrule=false;
         edit=true;
        try{
            Database.upsert(newrule);
            newrule = new Rule__c();
            return(new PageReference('/apex/AW_Rule_VF'));
        }
        catch(Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.Error,e.getDMLMessage(0));
            ApexPages.addMessage(msg);
            return null;
        }
        
    }    
    
    
}