force-app/main/default/objects/Advance_Workflow__c/Advance_Workflow__c.object-meta.xml
<CustomObject>
    <description>This object holds the definition of the workflows for standard and custom objects</description>
    <label>Advance Workflow</label>
    <nameField>
        <label>Advance Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advance Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advance_Workflow__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Holds the description of the Workflow</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Advance_Workflow__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Advance Workflow doesn&apos;t trigger rule execution until you activate it. To activate a workflow rule, click Enable on the workflow rule detail page. Click Deactivate to prevent  Advance Workflow rules associated to an object  from triggering</description>
    <inlineHelpText>Advance Workflow doesn&apos;t trigger rule execution until you activate it. To activate a workflow rule, click Enable on the workflow rule detail page. Click Deactivate to prevent  Advance Workflow rules associated to an object  from triggering</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Advance_Workflow__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</description>
    <inlineHelpText>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Advance_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Advance_Workflow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advance Workflow</label>
    <referenceTo>Advance_Workflow__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Evaluation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Rule__c</fullName>
    <label>Evaluation Rule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </value>
            <value>
                <fullName>Record is created</fullName>
            </value>
            <value>
                <fullName>Record is created or edited</fullName>
            </value>
            <value>
                <fullName>On Click Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/RuleAction__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RuleAction__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ccount Name</fullName>
            </value>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Site</fullName>
            </value>
            <value>
                <fullName>Account Source</fullName>
            </value>
            <value>
                <fullName>Annual Revenue</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Created By</fullName>
            </value>
            <value>
                <fullName>Data.com Key</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Last Modified By</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Parent Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>SIC Code</fullName>
            </value>
            <value>
                <fullName>SIC Description</fullName>
            </value>
            <value>
                <fullName>Ticker Symbol</fullName>
            </value>
            <value>
                <fullName>Type</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
                <default>true</default>
                <label>Number</label>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Multi-Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Long_Value__c.field-meta.xml
<CustomField>
    <fullName>Long_Value__c</fullName>
    <label>Long Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Notify_User__c.field-meta.xml
<CustomField>
    <fullName>Notify_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Update Field</fullName>
                <default>true</default>
                <label>Update Field</label>
            </value>
            <value>
                <fullName>Insert Related Object</fullName>
            </value>
            <value>
                <fullName>Insert Classification</fullName>
                <color>#FF0000</color>
                <label>Insert Classification</label>
            </value>
            <value>
                <fullName>Send Email</fullName>
            </value>
            <value>
                <fullName>Execute an Apex Job</fullName>
            </value>
            <value>
                <fullName>Apex Callout-HTTP</fullName>
            </value>
            <value>
                <fullName>Load Iframe</fullName>
            </value>
            <value>
                <fullName>Load a VF Page</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Attach Documents</fullName>
            </value>
            <value>
                <fullName>Chatter Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/RuleCriteria__c.object-meta.xml
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <label>Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RuleCriteria__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Multi-Picklist</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Matching_Type__c.field-meta.xml
<CustomField>
    <fullName>Matching_Type__c</fullName>
    <label>Matching Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not Equal To</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Does Not Contain</fullName>
            </value>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Ends With</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Greater Or Equal</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Less Or Equal</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
            <value>
                <fullName>Between</fullName>
            </value>
            <value>
                <fullName>Regular Expression</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Matching_Value__c.field-meta.xml
<CustomField>
    <fullName>Matching_Value__c</fullName>
    <label>Matching Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <label>Related Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleCriteria__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Criteria</relationshipLabel>
    <relationshipName>Rule_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Values_for_Action_Insert_Record__c/Values_for_Action_Insert_Record__c.object-meta.xml
<CustomObject>
    <description>Captures the values  for the Insert  Related Record Action</description>
    <label>Values for Action Insert Record</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Values for Action Insert Record</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Values_for_Action_Insert_Record__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value to be populated on field</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AW_ImportExport_Controller_Test.cls
//
// (c) 2012 Appirio, Inc.
// AW_ImportExport_Controller_Test                                                     
// Test Class for to parse AdvanceAW_ImportExport_Controller
//
// 24 Apr 2013     Peter Babalis     Original
//  
//
 @isTest
 public with sharing class AW_ImportExport_Controller_Test {
 static Advance_Workflow__c plan;
 static Rule__c rule2;
  
 @isTest
 static void TestescapecharsToch() {
        
        String str = 'ciao&hola';
         AW_ImportExport_Controller.escapecharsTochars(str);
    
    }
 /**
    * Test Export methods
    */
    
   public static testMethod void testexport() {
   PageReference pageRef = Page.AW_ImportExport_VF;
        Advance_Workflow__c advanceWF = new Advance_Workflow__c(Name ='advancewf',Object__c  = 'Account', Enabled__c=True,Description__c = 'Test Desc');
        insert advanceWF;
        
        Rule__c rule    =   new Rule__c(Name = 'Rule test1',
                                        Status__c = 'Draft',
                                        Object__c = 'Account', 
                                        Version__c = 1,
                                        Description__c = 'Rule 1 Description',
                                        Evaluation_Rule__c='Record is created or edited'
                                        //,Advance_Workflow__c = advanceWF.id
                                        );
        insert rule;
         
        RuleCriteria__c ruleCriteria    =   new RuleCriteria__c(Rule__c = rule.id,
        Related_Object__c='Account',
        Matching_Type__c='Equals', 
        Matching_Value__c='Apparel', 
        Field_name__c='Industry',
        Field_API_Name__c='Industry',
        Field_Type__c='Picklist');
        insert  ruleCriteria;
        
        RuleAction__c ruleAction        =   new RuleAction__c(Rule__c = rule.id,
        Related_Object__c='Account',
        Reference_Id__c=Userinfo.getUserId(),
        Field_Name__c='Industry',
        Field_API_Name__c='Industry',
        Type__c='Update Field',
        Value__c='Apparel',
        Long_Value__c=null,
        Notify_User__c=False,
        Email_Template__c=null
        );
      
           
          
        insert ruleAction;
 
        Values_for_Action_Insert_Record__c va   =   new Values_for_Action_Insert_Record__c(Name='name1',Rule_Action__c=ruleAction.id);
        insert va;
        
         
        rule.Order__c=10;
        rule.Status__c = 'Active';
        rule.Execution_Behavior__c='Execute and Exit';
        rule.Advance_Workflow__c=advanceWF.id;
        update rule;

      //  PageReference pageRef = Page.AW_ImportExport_VF;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', advanceWF.id);
        
        AW_ImportExport_Controller controller = new AW_ImportExport_Controller(); 
        
        // Instantiate a new controller with all parameters in the page
        controller = new AW_ImportExport_Controller();  
        controller.option = '1';
        controller.ruleOpt = '1';
        controller.exportProcess();
        
        controller.option = '1';
        controller.ruleOpt = '2';
        controller.exportProcess();
        
        controller.option = '1';
        controller.ruleOpt = '3';
        controller.exportProcess();
        
        controller.option = '0';
        controller.ruleOpt = '2';
        controller.exportProcess(); 
   }   
  /**
    * Test Controller methods
    */
   public static testMethod void testController() {
 	    PageReference pageRef = Page.AW_ImportExport_VF;
   	 	Test.setCurrentPage(pageRef);
   		AW_ImportExport_Controller controller = new AW_ImportExport_Controller();
        controller.option = '0';
        controller.ruleOpt = '2';
        controller.cancel();
        controller.checkAction();
        controller.getRadioOptions();
        controller.getRuleOptions();
        controller.start();
        controller.importProcess();
        
}
  
  
    public static void MyTest() {
          
        Advance_Workflow__c advanceWF = new Advance_Workflow__c(Name ='advancewf',Object__c  = 'Account', Enabled__c=True,Description__c = 'Test Desc');
        insert advanceWF;
        
        Rule__c rule    =   new Rule__c(Name = 'Rule test1',
                                        Status__c = 'Draft',
                                        Object__c = 'Account', 
                                        Version__c = 1,
                                        Description__c = 'Rule 1 Description',
                                        Evaluation_Rule__c='Record is created or edited'
                                        //,Advance_Workflow__c = advanceWF.id
                                        );
        insert rule;
         
        RuleCriteria__c ruleCriteria    =   new RuleCriteria__c(Rule__c = rule.id,
        Related_Object__c='Account',
        Matching_Type__c='Equals', 
        Matching_Value__c='Apparel', 
        Field_name__c='Industry',
        Field_API_Name__c='Industry',
        Field_Type__c='Picklist');
        insert  ruleCriteria;
        
        RuleAction__c ruleAction        =   new RuleAction__c(Rule__c = rule.id,
        Related_Object__c='Account',
        Reference_Id__c=Userinfo.getUserId(),
        Field_Name__c='Industry',
        Field_API_Name__c='Industry',
        Type__c='Update Field',
        Value__c='Apparel',
        Long_Value__c=null,
        Notify_User__c=False,
        Email_Template__c=null
        );
      
           
          
        insert ruleAction;
 
        Values_for_Action_Insert_Record__c va   =   new Values_for_Action_Insert_Record__c(Name='name1',Rule_Action__c=ruleAction.id);
        insert va;
        
         
        rule.Order__c=10;
        rule.Status__c = 'Active';
        rule.Execution_Behavior__c='Execute and Exit';
        rule.Advance_Workflow__c=advanceWF.id;
        update rule;
        
        
        PageReference pageRef = Page.AW_ImportExport_VF;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('id', advanceWF.id);
        
        AW_ImportExport_Controller controller = new AW_ImportExport_Controller(); 
        
        // Instantiate a new controller with all parameters in the page
        controller = new AW_ImportExport_Controller();  
        controller.option = '1';
        controller.ruleOpt = '3';
        controller.checkAction();
        controller.getRadioOptions();
        controller.getRuleOptions();
        controller.importProcess();
        controller.exportProcess();
        controller.cancel();
        controller.start();
        
            
        
    }   
 

}