force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <description>Used by G100 to compare Opportunities and pipeline to annual growth and performance goals. Primarily used in Reports and Dashboards.</description>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Goals__c/Goals__c.object-meta.xml
<CustomObject>
    <description>Performance Management Goals Record for V2R Process</description>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOL{000000}</displayFormat>
        <label>Goals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mid_Year_Review__c/Mid_Year_Review__c.object-meta.xml
<CustomObject>
    <description>Mid-Year Reviews</description>
    <label>Mid-Year Review</label>
    <nameField>
        <displayFormat>MYR{000000}</displayFormat>
        <label>Mid-Year Review No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mid-Year Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mid_Year_Review__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>To access your full Goal Record (including metrics), please right click on the Goal Record Name to open it in a new tab.</inlineHelpText>
    <label>Goal</label>
    <referenceTo>Goals__c</referenceTo>
    <relationshipLabel>Mid-Year Reviews</relationshipLabel>
    <relationshipName>Mid_Year_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year_end_Review__c/Year_end_Review__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Year-End Review</label>
    <nameField>
        <displayFormat>YER{000000}</displayFormat>
        <label>Year End Review No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Year-End Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Year_end_Review__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>To access your full Goal Record (including metrics), please right click on the Goal Record Name to open it in a new tab.</inlineHelpText>
    <label>Goal</label>
    <referenceTo>Goals__c</referenceTo>
    <relationshipName>Year_End_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Year_end_Review__c/fields/Mid_Year_Review__c.field-meta.xml
<CustomField>
    <fullName>Mid_Year_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mid-Year Review</label>
    <referenceTo>Mid_Year_Review__c</referenceTo>
    <relationshipName>Year_end_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/YearEndReviewTriggerHandler.cls
public class YearEndReviewTriggerHandler {
    public void YearEndReviewTriggerHandler(){
        
    }
    public void isInsertMethod(List<Year_end_Review__c> newList){
        
         Set<Id> MidYearIds = new Set<Id>();

        for (Year_end_Review__c yrs : newList){
        
            if(yrs.Mid_Year_Review__c!=null)
                MidYearIds.add(yrs.Mid_Year_Review__c);
        }
        
        map<Id,Id> RelatedGoals = new map<Id,Id>();
        if(MidYearIds.size()>0){

            for(Mid_Year_Review__c midyrs : [Select Id, Goal__r.Id from Mid_Year_Review__c where Id IN:MidYearIds]){
                if(!RelatedGoals.containsKey(midyrs.Id) ){
                    RelatedGoals.put(midyrs.Id,midyrs.Goal__r.Id);
                }
            }
        }
                            
       for (Year_end_Review__c yrs : newList){
        system.debug('=======>'+RelatedGoals);
            if(!RelatedGoals.isEmpty() && RelatedGoals.containsKey(yrs.Mid_Year_Review__c))
                yrs.Goal__c = RelatedGoals.get(yrs.Mid_Year_Review__c);
            
        }
        
    }
    
    public void isUpdateMethod(Map<Id,Year_end_Review__c> newMap,Map<Id,Year_end_Review__c> oldMap){
        Set<Id> MidYearIds = new Set<Id>();
        for(Year_end_Review__c  yrs: newMap.values()){
            if(oldMap.get(yrs.Id).Mid_Year_Review__c!=yrs.Mid_Year_Review__c){
                MidYearIds.add(yrs.Mid_Year_Review__c);
            }
        }
        
        map<Id,Id> RelatedGoals = new map<Id,Id>();
        if(MidYearIds.size()>0){

            for(Mid_Year_Review__c midyrs : [Select Id, Goal__r.Id from Mid_Year_Review__c where Id IN:MidYearIds]){
                if(!RelatedGoals.containsKey(midyrs.Id)){
                    RelatedGoals.put(midyrs.Id,midyrs.Goal__r.Id);
                }
            }
            
            
       }

       for(Year_end_Review__c  yrs: newMap.values()){
       system.debug('=======>RelatedGoals Counts===>'+RelatedGoals);
          
           if(RelatedGoals.containsKey(yrs.Mid_Year_Review__c)){
                   system.debug(yrs.Mid_Year_Review__c+'===In ELSE====>'+RelatedGoals);
                   
                  yrs.Goal__c = RelatedGoals.get(yrs.Mid_Year_Review__c);
           }
           system.debug('=======>'+ yrs.Goal__c);
       
       }
        
    }
}