force-app/main/default/objects/AdvanceWorkflowBatchStatus__c/AdvanceWorkflowBatchStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Will store the status of current running batch</description>
    <label>Advance Workflow Batch Status</label>
</CustomObject>

force-app/main/default/objects/Object_Action_Execution__c/Object_Action_Execution__c.object-meta.xml
<CustomObject>
    <label>Object Action Execution</label>
    <nameField>
        <label>Lookup Object Action Execution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Action Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Action_Execution__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lookup Object</fullName>
            </value>
            <value>
                <fullName>Bulk API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/RuleAction__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RuleAction__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ccount Name</fullName>
            </value>
            <value>
                <fullName>Account Number</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
            <value>
                <fullName>Account Site</fullName>
            </value>
            <value>
                <fullName>Account Source</fullName>
            </value>
            <value>
                <fullName>Annual Revenue</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Created By</fullName>
            </value>
            <value>
                <fullName>Data.com Key</fullName>
            </value>
            <value>
                <fullName>Description</fullName>
            </value>
            <value>
                <fullName>Employees</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
            <value>
                <fullName>Last Modified By</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Parent Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>SIC Code</fullName>
            </value>
            <value>
                <fullName>SIC Description</fullName>
            </value>
            <value>
                <fullName>Ticker Symbol</fullName>
            </value>
            <value>
                <fullName>Type</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Lookup_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Field_API_Name__c</fullName>
    <label>Lookup Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Lookup_Object__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Object__c</fullName>
    <label>Lookup Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RuleAction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Update Field</fullName>
                <default>true</default>
                <label>Update Field</label>
            </value>
            <value>
                <fullName>Insert Related Object</fullName>
            </value>
            <value>
                <fullName>Insert Classification</fullName>
                <color>#FF0000</color>
                <label>Insert Classification</label>
            </value>
            <value>
                <fullName>Send Email</fullName>
            </value>
            <value>
                <fullName>Execute an Apex Job</fullName>
            </value>
            <value>
                <fullName>Apex Callout-HTTP</fullName>
            </value>
            <value>
                <fullName>Load Iframe</fullName>
            </value>
            <value>
                <fullName>Load a VF Page</fullName>
            </value>
            <value>
                <fullName>Canvas</fullName>
            </value>
            <value>
                <fullName>Attach Documents</fullName>
            </value>
            <value>
                <fullName>Chatter Notification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AW_Advance_WorkflowBatch.cls
global with sharing class AW_Advance_WorkflowBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    private string query = '';
    private string sobjType = '';
    private DateTime dtnew = null;
    private DateTime dt = null;
    
    public AW_Advance_WorkflowBatch (DateTime dt1,String sobjType){
        this.sobjType = sobjType;
        this.dt = dt1;       
        query = 'Select Id,Action__c,Value__c,Record_Id__c FROM ' + sobjType ;//where CreatedDate >=:dt 
       
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        dtnew = system.now();
        return Database.getQueryLocator(query);
        /**
         * Setting the date context for next execute
         */     
    }
    
    global void execute(Database.BatchableContext BC, List<Object_Action_Execution__c> scope){
        Set<Id> actionIds = new Set<Id>();
        Set<Id> recordIds = new Set<Id>();
        Map<String,String> actionValue = new Map<String,String>();      
        for(Object_Action_Execution__c o: scope){
            actionIds.add(o.Action__c);
            recordIds.add(o.Record_Id__c);
            actionValue.put(o.Action__c,o.Value__c);
        }
       
      // List<RuleAction__c> actions =[Select Id,Type__c, Rule__c,Rule__r.Object__c,Lookup_Object__c,Lookup_Field_Api_Name__c,Lookup_Condition__c,Field_API_Name__c  ,Field_Name__c FROM RuleAction__c WHERE Id IN:actionIds];
       List<RuleAction__c> actions =[Select Id,Type__c, Rule__c,Rule__r.Object__c,Field_API_Name__c  ,Field_Name__c FROM RuleAction__c WHERE Id IN:actionIds];
       
       Set<Id> ruleIds = new Set<Id>();
       Set<Id> evaluateActions = new Set<Id>();
       String sobjectName;  
       
       for(RuleAction__c a:actions){
            //if(a.Type__c=='Update Field' && a.Field_Name__c=='LookupObject')
            //    continue;
                
            ruleIds.add(a.Rule__c);
            evaluateActions.add(a.Id);
            sobjectName =a.Rule__r.Object__c; 
       }
       
       AW_AdvanceWorkflowExecutionEngine.bulkOperation=true;     
       AW_AdvanceWorkflowExecutionEngine.bulkactionIds=evaluateActions;   
       AW_AdvanceWorkflowExecutionEngine.evaluateRules(ruleIds,recordIds,sobjectName );
       
       
       
       delete scope;
       
    }
    
    global void finish(Database.BatchableContext BC) {
        //schedule for next run after some time
        //string query = 'Select id from ' + sobjType + ' where CreatedDate >=:dtnew ' + ' limit 1';
        
        string query = 'Select id from ' + sobjType + ' limit 1';
        
        List<SObject> lstObj = Database.query(query);
        if(lstObj != null && lstObj.size() > 0){
            AW_AdvanceWorkflowExecutionHelper.StartAWSchedular(system.now(),sobjType);
        }else{
            AdvanceWorkflowBatchStatus__c awBatchStatus = AdvanceWorkflowBatchStatus__c.getInstance(sobjType);
            if(awBatchStatus != null){
                delete awBatchStatus;
            }
        }
    }

}