force-app/main/default/objects/Contact_Team__c/Contact_Team__c.object-meta.xml
<CustomObject>
    <label>Contact Team</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Teams</relationshipLabel>
    <relationshipName>Contact_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CEO Works Primary</fullName>
            </value>
            <value>
                <fullName>CEO Works Secondary</fullName>
            </value>
            <value>
                <fullName>CEO Works Tertiary</fullName>
            </value>
            <value>
                <fullName>G100 Primary</fullName>
            </value>
            <value>
                <fullName>G100 Secondary</fullName>
            </value>
            <value>
                <fullName>G100 Tertiary</fullName>
            </value>
            <value>
                <fullName>HLG Primary</fullName>
            </value>
            <value>
                <fullName>HLG Secondary</fullName>
            </value>
            <value>
                <fullName>HLG Tertiary</fullName>
            </value>
            <value>
                <fullName>SSA Primary</fullName>
            </value>
            <value>
                <fullName>SSA Secondary</fullName>
            </value>
            <value>
                <fullName>SSA Tertiary</fullName>
            </value>
            <value>
                <fullName>TMG Primary</fullName>
            </value>
            <value>
                <fullName>TMG Secondary</fullName>
            </value>
            <value>
                <fullName>TMG Tertiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>PSA Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Teams (Team Member)</relationshipLabel>
    <relationshipName>Contact_Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchUpdateContactTeamOnContact.cls
/*************************************************************************
Name : BatchUpdateContactTeamOnContact
Author : Jyoti Singh (Appirio JDC)
Date :  7th Mar , 2014
Usage : This class is used to update Contact data.
**************************************************************************/
global class BatchUpdateContactTeamOnContact implements Database.Batchable<SObject>{
    
    //DataBase.Batchable Start method
    global database.querylocator start(Database.BatchableContext BC){
       
       String query = 'Select id from Contact ';                    
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, LIST<SObject> listData){
         List<Contact> contactLists = (List<Contact>)listData;         
         
         List<Contact_Team__c > contactTeams = new List<Contact_Team__c>([Select Team_Member__r.Name, Team_Member__c, Contact__c From Contact_Team__c where Contact__c in : contactLists and Team_Member__c!= Null order by Role__c ASC]);
         Map<ID , String> mapContatTeams  = new Map<ID , String>();
         if(contactTeams.size() > 0){
             for(Contact_Team__c  cont : contactTeams){
                 String partnerNames = '';
                 if(mapContatTeams.ContainsKey(cont.Contact__c) && cont.Team_Member__c != null){
                     partnerNames = mapContatTeams.get(cont.Contact__c) + ', '+ cont.Team_Member__r.Name;
                 }  
                 else if(cont.Team_Member__c != null){
                     partnerNames = cont.Team_Member__r.name;
                 }
                 mapContatTeams.put(cont.Contact__c ,partnerNames );
             }
             
             List<Contact> contacts = new List<Contact>();
             
             for(Id cntct : mapContatTeams.keyset()){
                 contacts.Add(new Contact(Id = cntct , Contact_Team_Members__c= mapContatTeams.get(cntct ) ));
             }
             //system.debug('==='+contactSpouse);
             database.update(contacts , false);
         }
         
    }
    
    global void finish(Database.BatchableContext BC){
         
    }
    
    /** COMMENTED START by Rohit for S-635394
     public static testmethod void BatchUpdateContactTeamOnContactTest(){
          BatchUpdateContactTeamOnContact contactBatch = new BatchUpdateContactTeamOnContact ();     
          Test.startTest();
          Database.executeBatch(contactBatch , 1);
          Test.stopTest();
       }
     COMMENTED END by Rohit for S-635394**/
    
   }