force-app/main/default/objects/Contact_Team__c/Contact_Team__c.object-meta.xml
<CustomObject>
    <label>Contact Team</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Team Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Teams</relationshipLabel>
    <relationshipName>Contact_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CEO Works Primary</fullName>
            </value>
            <value>
                <fullName>CEO Works Secondary</fullName>
            </value>
            <value>
                <fullName>CEO Works Tertiary</fullName>
            </value>
            <value>
                <fullName>G100 Primary</fullName>
            </value>
            <value>
                <fullName>G100 Secondary</fullName>
            </value>
            <value>
                <fullName>G100 Tertiary</fullName>
            </value>
            <value>
                <fullName>HLG Primary</fullName>
            </value>
            <value>
                <fullName>HLG Secondary</fullName>
            </value>
            <value>
                <fullName>HLG Tertiary</fullName>
            </value>
            <value>
                <fullName>SSA Primary</fullName>
            </value>
            <value>
                <fullName>SSA Secondary</fullName>
            </value>
            <value>
                <fullName>SSA Tertiary</fullName>
            </value>
            <value>
                <fullName>TMG Primary</fullName>
            </value>
            <value>
                <fullName>TMG Secondary</fullName>
            </value>
            <value>
                <fullName>TMG Tertiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Team__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>PSA Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Teams (Team Member)</relationshipLabel>
    <relationshipName>Contact_Teams1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactTeamTriggerHandler.cls
/***********************************************************************************************
Name : ContactTeamTriggerHandler
Created Date : 7th March , 2014
Created By : Jyoti Singh
Description : S-194517           
***********************************************************************************************/

public without sharing class ContactTeamTriggerHandler{
  private static final String DELIMITER = ', ';
 
  //Call Method on Delete
  public static void onAfterDelete(List<Contact_Team__c> oldMemberList) {
    populateTeamMebers(getContactIdsFromContactTeam(oldMemberList));
  }
  
  //Call Method on Insert
  public static void onAfterInsert(List<Contact_Team__c> newMemberList) {
    populateTeamMebers(getContactIdsFromContactTeam(newMemberList));
  }

  //Call Method on Undelete
  public static void onAfterUndelete(List<Contact_Team__c> newMemberList) {
    populateTeamMebers(getContactIdsFromContactTeam(newMemberList));
  }

  //Call Method on Update
  public static void onAfterUpdate(List<Contact_Team__c> oldMemberList,
    Map<Id, Contact_Team__c> newMemberMap) {

    Set<Id> parentIds = new Set<Id>();
     
    for (Contact_Team__c oldMember : oldMemberList) {
      Id newParent = newMemberMap.get(oldMember.Id).Contact__c;
      Id newMember = newMemberMap.get(oldMember.Id).Team_Member__c;
      if (oldMember.Contact__c != newParent) {
        if (oldMember.Contact__c != null) {
          parentIds.add(oldMember.Contact__c);
        }
        if (newParent != null) {
          parentIds.add(newParent);
        }
      }
      if (oldMember.Team_Member__c != newMember) {
        if (oldMember.Contact__c != null) {
          parentIds.add(oldMember.Contact__c);
        }
        if (newMember != null) {
          parentIds.add(newParent);
        }        
      }
      
    }
    
    //Recalculate names
    populateTeamMebers(parentIds);
  }


  //Perform the logic
  private static void populateTeamMebers(Set<Id> parentIds) {
    Map<Id, Set<String>> teamMap = new Map<Id, Set<String>>();
    
    //Create a map of Id and set of string.
    for (Id parentId : parentIds) {
      teamMap.put(parentId, new Set<String>());
    }
    
    //Create a map of Contact id and set of contact team member's names.
    for (Contact_Team__c contTeam  : [Select Team_Member__r.Name, Team_Member__c, Role__c,Contact__c From Contact_Team__c
                           where Contact__c in :parentIds order by Role__c Asc]) {
      if(contTeam.Contact__c != null && contTeam.Team_Member__c != null && teamMap.ContainsKey(contTeam.Contact__c)){
          teamMap.get(contTeam.Contact__c).add(contTeam.Team_Member__r.Name);
            }
    }
    
    //Create list of contacts to update
    List<Contact> contactsToUpdate = new List<Contact>();
    for (Id parentId : teamMap.keySet()) {
        String partners = generateContcatTeamMembersNames(teamMap.get(parentId));
        contactsToUpdate.add(new Contact(Id = parentId,Contact_Team_Members__c = partners));
    }

    if (contactsToUpdate.size() > 0) {
      update contactsToUpdate;
    }
  }
 
  //return a comma seprated string .
  private static String generateContcatTeamMembersNames(Set<String> teamMembers) {
    List<String> teamMemberList = new List<String>();
    teamMemberList.addAll(teamMembers);
    if(teamMemberList.size() > 0)
        return String.join(teamMemberList, DELIMITER);
    return '';
  }

 //Create a set of contact IDs
  private static Set<Id> getContactIdsFromContactTeam(List<Contact_Team__c> contactTeam) {
    Set<Id> parentIds = new Set<Id>();
    for (Contact_Team__c contTeam : contactTeam) {
      if (contTeam.Contact__c != null) {
        parentIds.add(contTeam.Contact__c);
      }
    }
    return parentIds;
  }
}