force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Members__c/Event_Members__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Event Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Members__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Members__c/fields/Day_1_Role__c.field-meta.xml
<CustomField>
    <fullName>Day_1_Role__c</fullName>
    <label>Day 1 Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited Member</fullName>
            </value>
            <value>
                <fullName>Invited Advisor</fullName>
            </value>
            <value>
                <fullName>Invited Prospect</fullName>
            </value>
            <value>
                <fullName>Invited Speaker</fullName>
            </value>
            <value>
                <fullName>Invited Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Session Chair</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>CHRO - Not Attending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Invited</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Members__c/fields/Day_2_Role__c.field-meta.xml
<CustomField>
    <fullName>Day_2_Role__c</fullName>
    <label>Day 2 Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invited Member</fullName>
            </value>
            <value>
                <fullName>Invited Advisor</fullName>
            </value>
            <value>
                <fullName>Invited Prospect</fullName>
            </value>
            <value>
                <fullName>Invited Speaker</fullName>
            </value>
            <value>
                <fullName>Invited Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Session Chair</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>CHRO - Not Attending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Not Invited</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Tentative</fullName>
            </value>
            <value>
                <fullName>Member Designate</fullName>
            </value>
            <value>
                <fullName>Not Attending - Sent Designate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Members__c/fields/Day_3_Role__c.field-meta.xml
<CustomField>
    <fullName>Day_3_Role__c</fullName>
    <description>Role of the attendee on day three (applies to Women&apos;s Leadership Acceleration)</description>
    <label>Day 3 Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited Member</fullName>
            </value>
            <value>
                <fullName>Invited Advisor</fullName>
            </value>
            <value>
                <fullName>Invited Prospect</fullName>
            </value>
            <value>
                <fullName>Invited Speaker</fullName>
            </value>
            <value>
                <fullName>Invited Guest</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Speaker</fullName>
            </value>
            <value>
                <fullName>Guest</fullName>
            </value>
            <value>
                <fullName>Session Chair</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>CHRO - Not Attending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Members__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomEventTriggerHandler.cls
/*********************************************************************************
Name : Nitin Vyas
Created By : Appirio  
Created Date : 2 Jan 2019
Purpose : it is a trigger handler for Custom Event 
*********************************************************************************/
public class CustomEventTriggerHandler {
    public static void updateCountForMeetingAttended(Map<Id,Event__c> newMap,Map<Id,Event__c> oldVal,String status) {
        
        Set<Id> contactSetId = new Set<Id>();
        Map<Id,List<Event_Members__c>> insertRecord = new Map<Id,List<Event_Members__c>>();
        Map<Id,Integer> eventMap = new Map<Id,Integer>();
        List<Contact> conLstWthNumber = new List<Contact>();
        List<Event_Members__c> evtMemLst;
        
        if(status == 'afterUpdate') {
            evtMemLst = [Select id from Event_Members__c where Event__c IN: oldVal.keySet()];
            
            evtMemLst.addAll([Select id from Event_Members__c where Event__c IN: newMap.keySet()]);               
        }
        
        if(status == 'afterUndelete') {
            evtMemLst = [Select id from Event_Members__c where Event__c IN: newMap.keySet()];
        }
        
        if(status == 'afterDelete') {
            evtMemLst = [Select id from Event_Members__c where Event__c IN: oldVal.keySet()];
        }
        
        if(evtMemLst!=null && !evtMemLst.isEmpty()) {
            for(Event_Members__c evtCon : [Select id,Contact__c from Event_Members__c where id IN: evtMemLst]) {
                contactSetId.add(evtCon.Contact__c);
            }	
            
            for(Contact con : [Select Id,Name,Account_Name__c,(SELECT Day_1_Role__c,	Day_2_Role__c,Day_3_Role__c,Event_End_Date__c 
                                                               FROM Event_Members__r 
                                                               WHERE Event_End_Date__c !=null) 
                               From Contact
                               WHERE Id IN : contactSetId]) {
                                   insertRecord.put(con.Id,con.Event_Members__r);                             
                               }
            
            for(Id conId : insertRecord.keySet()) {
                for(Event_Members__c em : insertRecord.get(conId)) {
                    if(em.Event_End_Date__c > (Date.today()-395) &&
                       ((em.Day_1_Role__c=='Guest' || 
                         em.Day_1_Role__c=='Prospect' ||
                         em.Day_1_Role__c=='Member' ||
                         em.Day_1_Role__c=='Advisor') ||
                        (em.Day_2_Role__c=='Guest' || 
                         em.Day_2_Role__c=='Prospect' ||
                         em.Day_2_Role__c=='Member' ||
                         em.Day_2_Role__c=='Advisor') ||
                        em.Day_3_Role__c=='Guest' || 
                        em.Day_3_Role__c=='Prospect' ||
                        em.Day_3_Role__c=='Member' ||
                        em.Day_3_Role__c=='Advisor')) {
                            
                            if(!eventMap.containsKey(conId)) {
                                eventMap.put(conId,1);
                            }
                            else {
                                Integer count = eventMap.get(conId);
                                count = count+1;
                                eventMap.put(conId,count);
                            }
                        }
                }
            }
            
            for(Id conIdSetVal : contactSetId) {
                if(!eventMap.containsKey(conIdSetVal)) {
                    Contact con = new Contact();
                    con.Id=conIdSetVal;
                    con.Number_of_meetings_Attended__c = null;
                    conLstWthNumber.add(con);
                }
            }
            
            for(Id conIdVal : eventMap.keySet()) {
                Contact con = new Contact();
                con.Id=conIdVal;
                con.Number_of_meetings_Attended__c = eventMap.get(conIdVal);
                conLstWthNumber.add(con);
            }
            
            if(conLstWthNumber!=null && !conLstWthNumber.isEmpty()) {
                update conLstWthNumber;
            }  
        }
        
        
        
    }
}