force-app/main/default/objects/Milestone1_Task__c/Milestone1_Task__c.object-meta.xml
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <label>TMG Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone1_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The user responsible for completing the task.</inlineHelpText>
    <label>Assigned To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Tasks_Assigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The general description of the task. For example, what is the purpose of the task.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>Task Target Due Date</inlineHelpText>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/First_Chair_User__c.field-meta.xml
<CustomField>
    <fullName>First_Chair_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Chair</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Miles Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>Created for Story S-349354</description>
    <formula>Project_Milestone__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone1_Task__c/fields/Task_Stage__c.field-meta.xml
<CustomField>
    <fullName>Task_Stage__c</fullName>
    <defaultValue>&quot;Pending Approval&quot;</defaultValue>
    <inlineHelpText>Where is this task on the road to completion?</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Assigned</fullName>
            </value>
            <value>
                <fullName>To Be Scheduled</fullName>
            </value>
            <value>
                <fullName>Client Contacted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled by TMG</fullName>
            </value>
            <value>
                <fullName>Cancelled by Client</fullName>
            </value>
            <value>
                <fullName>TBR (To Be Rescheduled)</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>To Be Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Confirmed</fullName>
            </value>
            <value>
                <fullName>Not Attending</fullName>
            </value>
            <value>
                <fullName>Incomplete (Calendar Conflicts)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DueDateTaskDetailsExtension.cls
/*********************************************************************************
Name : Jyotirmaya Rath
Created By : Appirio  
Created Date : 03 Nov 2015
Purpose : VF page Controller to display all Due date task
 *********************************************************************************/
public without sharing class DueDateTaskDetailsExtension {
    
    // Page Variables
    public Milestone1_Task__c dueTask{get;set;}
    public String taskId{get;set;}
    public Boolean showQuestion{get;set;}
    public boolean ansNo{get;set;}
    public Date taskDueDate{get;set;}
    public string comments {get;set;}
    public String stage{get;set;}
    public List<Selectoption> taskStage {get;set;}
    // Controller of the class
    Public DueDateTaskDetailsExtension(ApexPages.StandardController con){
        init();
    }
    
    //initial all Page Variables
    private void init(){
        showQuestion = true ;
        ansNo = false ;
        taskId = ApexPages.currentPage().getParameters().get('Id');  
        taskStage = new List<SelectOption>();

        for(Schema.PicklistEntry ple : Milestone1_Task__c.Task_Stage__c.getDescribe().getPicklistValues()){
            taskStage.add(new Selectoption(ple.getLabel(),ple.getLabel()));        
        }
        if(!String.isBlank(taskId)){
          //S-369108 added harendra recordType.name in query
            for(Milestone1_Task__c t: [SELECT First_Chair_User__c, id,Name,recordType.name, Assigned_To__c,Assigned_To__r.name,Project_Name__c,
                                       Scheduled_Date__c,Task_Stage__c,Description__c,Due_Date__c 
                                       FROM Milestone1_Task__c WHERE id=:taskId ]){
                dueTask = t;     
            }
        }
    }
     
    // If Tassk Is completed
    public pageReference  answerYes(){
        String ans = ApexPages.currentPage().getParameters().get('ans'); 
        if(ans.toLowerCase() == 'yes'){
            system.debug(' yes');
            try{
                dueTask.Task_Stage__c = 'Complete';
                update dueTask;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Confirm,'Thank You'));
                showQuestion = false ;
            }
            catch(Exception e){
                System.debug('Failed To update');
            }
        }    
        Else  if(ans.toLowerCase() == 'no'){
            showQuestion = true ;
        }
        return null;
    }
    
 
    // submit Task Is not completed
    public pageReference submitTask(){
        try{    

            update dueTask ;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.Confirm,'Thank You'));
            showQuestion = false ;
            }
        catch(Exception e){
            System.debug('Failed To update->'+e.getMessage());
        }        
        return null;
    }
}