force-app/main/default/objects/TMG_Coaching_Guide__c/TMG_Coaching_Guide__c.object-meta.xml
<CustomObject>
    <label>TMG Coaching Guides</label>
    <nameField>
        <label>TMG Coaching Guides ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Coaching Guides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Content_Viewed__c/TMG_Content_Viewed__c.object-meta.xml
<CustomObject>
    <label>TMG Content Viewed</label>
    <nameField>
        <label>TMG Videos/Coaching Notes Viewed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMG Contents Viewed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TMG_Content_Viewed__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>TMG Contents Viewed</relationshipLabel>
    <relationshipName>TMG_Contents_Viewed</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TMG_Content_Viewed__c/fields/From_LU__c.field-meta.xml
<CustomField>
    <fullName>From_LU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TMG_Contents_Viewed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TMG_Content_Viewed__c/fields/TMG_Coaching_Guides__c.field-meta.xml
<CustomField>
    <fullName>TMG_Coaching_Guides__c</fullName>
    <label>TMG Coaching Guide ID</label>
    <referenceTo>TMG_Coaching_Guide__c</referenceTo>
    <relationshipLabel>TMG Contents Viewed</relationshipLabel>
    <relationshipName>TMG_Contents_Viewed</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TMG_Content_Viewed__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TMGCoachingSlidesCreation.cls
/***********************************************************************************************************
* Appirio, Inc
* Name          : TMGCoachingSlidesCreation
* Created By    : Shivani Jain(Appirio)
* Purpose       : Create TMG Coaching Slides for Email Attachments received on coachingplans@miles-group.com
* Created Date  : 17/02/2019
*
* Date Modified                Modified By             Description of the update
* Updated By    : Lokesh Korani(Appirio)
* Purpose       : Create TMG Content View records for Email  received on coachingplans@miles-group.com
* Updated Date  : 12/07/2020
*
* Date Modified                Modified By             Description of the update

----------------------------------------------------------------------------------------------------------
* [Date]                       [Person Name]           [Short Description]
**********************************************************************************************************/
global class TMGCoachingSlidesCreation implements Messaging.InboundEmailHandler {
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        //START, Changes updated by Lokesh Korani on 12/07/2020 for Story :S-665486 (Create TMG Content View records for Email)
        Set<String> emails = new Set<String>();
        Map<String,Id> emailToConMap = new Map<String, Id>();
        Map<String, String> IdToURLMap = new Map<String, String>();
        string cavanEmail = '';
        user fromUser;
         if(email != NULL) {
        for(Contact con : [SELECT id,Email,Name from Contact where Email IN: email.toAddresses   ]) {
            emailToConMap.put(con.Email, con.id);
        }
        for(user U : [Select id,email from user where Email =: email.fromAddress or id=: Label.Cavan_Email]){
            if(string.valueof(U.id).substring(0,15)== Label.Cavan_Email){
               cavanEmail = u.email; 
                 if(email.fromAddress == u.email){
                    fromUser = u;
                }
            }
            else{
            fromUser = u;
            }
        }
            Set<String> NewList =New Set<String>();
            if (email.plainTextBody != null) { 
                for (String line : email.plainTextBody.split('\n')) { 
                    for (String row : line.split(' ')) {
                    TMG_Content_Viewed__c tCoachSlide = new TMG_Content_Viewed__c();
                    row = row.trim();
                    if(row.contains(System.Label.URLTmgContentView)) {
                        String Ab = row.replaceAll(' ', '');
                        Integer A= Ab.lastIndexOf('/');
                        NewList.add(Ab.right(Ab.length()-A-1));
                    }
                }
                }
            }
            set<string> contactnotExist = new set<string>();
            List<TMG_Content_Viewed__c	> contentViewToBeInserted = new list<TMG_Content_Viewed__c	>();
            If(NewList.size()>0){
            for(TMG_Coaching_Guide__c	 cg : [Select id,name from TMG_Coaching_Guide__c	 where name in :NewList ]){
                Newlist.remove(cg.name);
                for(String emailAddress: Email.toAddresses){
                    if(!emailToConMap.ContainsKey(emailAddress)){
                        contactnotExist.add(emailAddress);
                    }
                    else{
                    contentViewToBeInserted.add(new TMG_Content_Viewed__c(TMG_Coaching_Guides__c=cg.id,Contact__c = emailToConMap.get(emailAddress), From_lu__c = fromUser!= null?fromUser.id:null,Date_Sent__c=System.today(),Sent__c=TRUE,To__c = emailAddress));
                }
                }
                
            }
            }
            if(!contentViewToBeInserted.isEmpty()){
                try{
                    Database.insert(contentViewToBeInserted,false);
                }catch(exception e){
                    
                }
            }
            Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage>();
            if(!Newlist.isEmpty() ){
                for(string s: Newlist){
                    messages.add(createEmail(email.toAddresses,email.fromAddress,s,cavanEmail));
                }
            }    
            if(!contactnotExist.isEmpty() ){
                for(string s: contactnotExist){
                   
                    messages.add(createEmail(email.toAddresses,email.fromAddress,s,cavanEmail));
                }   
            }
            if(!messages.isEmpty()){ 
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            }
         }
        return result;
    }
    

Public static Messaging.SingleEmailMessage CreateEmail(list<string> toAddress, string fromAddress, string ID ,string cavanEmail){
     Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();    
                    message.toAddresses = new String[] { System.Label.TmgContentViewRecords,CavanEmail };
                        message.subject = System.Label.TmgContentViewSubject;
                    message.plainTextBody = Label.TmgContentViewBody +'\n'+
                        '\n TO: '+string.join(new list<string>(toAddress),';')+'\n'+
                        '\n FROM: '+fromAddress+'\n'+
                        '\n ID: '+id+'\n'+
                        '\n Date: '+date.today();
    return message;
    
}
     //END, Changes updated by Lokesh Korani on 12/07/2020 for Story :S-665486 (Create TMG Content View records for Email)
}